### ISSUE TITLE
How to get an "Image" instance from decoded image file data (base64)

### ISSUE THREAD

**Issue by ZhangChen199102** [django-cms/django-filer#1023]
I'm using `FilerImageField` in my model (Recipe):
`photo = FilerImageField(null=True, blank=True, related_name="recipe_photo", )`

I tried to upload a encoded image file data (base64) to server, then decode it and get a ContentFile object by using `ContentFile(decoded_image_data)`.

The issue is I got an error in `serializer.is_valid()`:
 `Exception Value: Cannot assign "<ContentFile: Raw content>": "Recipe.photo" must be a "Image" instance.`

I'm wondering how can I get an 'Image' instance from decoded image data, or convert "ContentFile" to "Image".

**Comment by kyale-mwendwa** [comment]
did you ever find away to resolve this issue ?

**Comment by stuaxo** [comment]
Looking through these old tickets I get the feeling Divio doesn't have the resources to address them.

**Comment by stuaxo** [comment]
Hey stalebot this is still an issue.

**Comment by sicksid** [comment]
you need to create a record with Filer.Image field and add your ContentFile to the file attribute then use that Filer.Image instance and it will work:

example that works with my code:


```
        file = request.FILES["file"]
        contract = self.get_object()

        filer_file = File.objects.create(
            file=DjangoFile(file, file.name),
            name=file.name,
            owner=request.user,
        )
        document = ContractDocument.objects.create(
            file=filer_file,
            user=request.user,
            contract=contract,
            status="draft",
        )
```
