### ISSUE TITLE
 it is compatible with django 2.0?

### ISSUE THREAD

**Issue by lidymonteirowm** [django-cms/django-filer#1026]
If not, whats upgrade forecast to be?

**Comment by dmnBrest** [comment]
The same here!
I try to install DjangoFiler to 2.0 and receive this error
...
  File "/usr/local/lib/python3.6/site-packages/filer/models/__init__.py", line 3, in <module>
    from .clipboardmodels import *  # flake8: noqa
  File "/usr/local/lib/python3.6/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from . import filemodels
  File "/usr/local/lib/python3.6/site-packages/filer/models/filemodels.py", line 10, in <module>
    from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'

**Comment by lerkgridhaus** [comment]
@dmnBrest I did the same and received the error too. I believe what happened was that Django 2.0 was uninstalled and 1.11 was installed automatically when doing pip install django-filer

**Comment by n2o** [comment]
Same problem here. Would be great to have this plugin in Django 2

**Comment by ebdavison** [comment]
Agreed that support for Django 2.0.1 would be needed.  I am actually trying to use django-crispy-forms and django-filer does not support Django 2.0.1 which is keeping me from using crispy.  Any plans to fix this?

**Comment by Wegi** [comment]
Any Upgrade on the horizon yet?

**Comment by frague59** [comment]
+1

**Comment by admed** [comment]
+1

**Comment by cyberbudy** [comment]
+1

**Comment by admed** [comment]
There is django 2.0 support  (only 2.0 higher are still not finished) but not merged yet. You can find it here: https://github.com/wooyek/django-filer/tree/feature/django2-support

**Comment by peterfarrell** [comment]
We are up against the wall as well and needing Django 2.0 support. Is there an ETA on the this PR #1096 ?
