### ISSUE TITLE
Chinese translation not working for Django1.10 and after.

### ISSUE THREAD

**Issue by xahhy** [django-cms/django-filer#1032]
I found that in master branch the locale folder for Chinese named **zh-Hans**，it should be **zh_Hans**。

It take me for a whole afternoon to find out this problem....
But I see in the develop branch, this problem is also there!
Hopefully the author can update the master branch by renaming the locale folder **zh-Hans**. So I can get the write version from pip. 
Thanks!

**Comment by yakky** [comment]
It's set as "zh-Hans" by transifex, and I am wondering why :thinking: 
I will investigate, thanks for reporting
