### ISSUE TITLE
Django 2.0 issues

### ISSUE THREAD

**Issue by FabriceSalvaire** [django-cms/django-filer#1045]
I applied the PR #1037

In **Admin**, I discovered field's **medias are placed in front** of the list, thus js like popup_handling are loaded before jquery. I fixed this  with

```
class AdminFileWidget(ForeignKeyRawIdWidget):
    class Media(object)
        js = (
            'admin/js/vendor/jquery/jquery.js',
            'admin/js/jquery.init.js',
            'filer/js/libs/dropzone.min.js',
            'filer/js/addons/dropzone.init.js',
            'filer/js/addons/popup_handling.js',
            'filer/js/addons/widget.js',
        )
```
I don't figured out the explanation in https://docs.djangoproject.com/en/2.0/topics/forms/media/

Moreover there is a typo in the context of the **AdminFileWidget**, obj should be file_obj, code need cleanup ...

```
class AdminFileWidget(ForeignKeyRawIdWidget):
  context = {
            'object': file_obj,
```

**Comment by lsmoker** [comment]
For the file_obj issue at [https://github.com/divio/django-filer/blob/006a1cfbdb5f61b6725b7675c7f9117e85b5d367/filer/fields/file.py#L61](url), a better fix is to replace
`obj = self.rel.to._default_manager.get(**{key: value})` at line 79 with
`obj = self.rel.remote_field.related_model._default_manager.get(**{key: value})`
`rel.to` is removed from django2.0 but the try/except catches this error and hides that fact.
I'm sure there is a more complete fix, but this works okay for me.
