### ISSUE TITLE
Polymorphic Error

### ISSUE THREAD

**Issue by SillyInventor** [django-cms/django-filer#1046]
Recently someone noted that our old filer folders are broken. I don't know when exactly that happened, but when you go to them you get:
```
DoesNotExist at /admin/filer/folder/20/list/
ContentType matching query does not exist.
```

The error is generated on line 348 of admin/folderadmin.py while calling line 90 of polymophic/models.py.

**Comment by yakky** [comment]
Have you deleted some models (as in "class definitions") or moved data from one database to another?
That error is triggered when one file is tagged with a content type which no longer exists. Can you check if all the values in ``filer_file.polymorphic_ctype_id`` matches the ones in ``django_content_type``

**Comment by JacoBezuidenhout** [comment]
I am having the same problem but I am using Postgres Schemas for multi-tenancy. On brand new tenants I get an error after uploading files into a folder. Does filer cache content types perhaps? So when I switch from one tenant to another then the cached value is used and not the content_type_id from the current schema.
