### ISSUE TITLE
Store canonical path in the model

### ISSUE THREAD

**Issue by yakky** [django-cms/django-filer#1056]
From https://github.com/divio/django-filer/pull/995#issuecomment-316676141

```
Maybe we should store the canonical URL in the database instead since it is not supposed to ever change. Then the logic for generating the URL can be changed or customised over time without breaking existing links.
```

**Comment by bogdan-decode** [comment]
+1  A lot of my data is broken because the times are off by one hour. Not sure how -- multiple migrations or server moves or maybe just life.  Storing once in the model would be robust.
