### ISSUE TITLE
The use of variables in thumbnail crop

### ISSUE THREAD

**Issue by mwenom** [django-cms/django-filer#1090]
Is there an option in this design
{% load thumbnail %}
{% thumbnail company.logo 250x250 crop %}

use the values of variables from models
{% load thumbnail %}
{% thumbnail company.logo instance.width x instance.height crop %}

that is, replace the numerical values with variables

**Comment by benzkji** [comment]
you'll need to make it a propertey of your model.

    @property
    def image_size(self):
        return (self.width, self.height)
        # or return "{}x{}".format(self.width, self.height)

    # template
    {% thumbnail company.logo company.image_size crop %}
