### ISSUE TITLE
Default upload folder per field

### ISSUE THREAD

**Issue by tehfink** [django-cms/django-filer#1098]
Apologies if this has already been addressed, but I didn't see it in the documentation. Is it possible to define a default folder where, e.g. an image will be uploaded, rather than having everything uploaded to "Unsorted Uploads"? Something like:

```python
class Company(models.Model):
    logo = FilerImageField(null=True, blank=True, related_name="logo", default_folder="logos")
    disclaimer = FilerFileField(null=True, blank=True, related_name="disclaimer_company", default_folder="documents")
```

**Comment by mhozza** [comment]
I'd be interested in implementing this.

There are 2 options here:

1. _id_ based - in this case you'd specify the folder id to put the files in.
2. _path_ based - in this case you'd specify the logical path to the folder to put the files in. The id would be computed by traversing the path, and if the folders does not exist, it should be created.

The 1. is simple option, easy to implement and probably sufficient, as the id retrieval can be done by the app using it. 2. is just for convenience and I'd be happy to do that as well if it is sth maintainers would want.

Question for maintainers: Are you interested in having this functionality?

**Comment by benzkji** [comment]
I've implemented something like this through django signals.

**Comment by benzkji** [comment]
I correct myself. Signals (only) wont work...needs to be built in, or many changes/overrides are needed, at minimum in the field/widget (provide folder to save to, for the upload request), and in the upload handling code (actually save to requested folder).

**Comment by qodrinzo** [comment]
+1 for this feature

**Comment by benzkji** [comment]
this would help a lot to unclutter drag and drop uploaded (into "unfiled files") files.
