### ISSUE TITLE
Use custom django storage

### ISSUE THREAD

**Issue by MediacraftFR** [django-cms/django-filer#1102]
Hello,

I would like to know if we can use a custom django storage in django filer ? For example : https://github.com/maddevsio/django_minio

Or maybe it's planned to be added soon ?

Thanks
Regards,

**Comment by benzkji** [comment]
you can, probably, using the FILER_STORAGES settings, check the docs.

https://django-filer.readthedocs.io/en/latest/settings.html#filer-storages

**Comment by benzkji** [comment]
as far as I know, it's used with AWS's S3, for example.
