### ISSUE TITLE
Bug: checkbox missing in file select dialog

### ISSUE THREAD

**Issue by rasovica** [django-cms/django-filer#1104]
Hi!

I have updated filer version to 1.3.2 and the checkboxes in the file selector popup have disappeared

In the rendered css there is the column:
`<td class="column-checkbox"></td>`
But as you can see it is empty.

Do you know why and how to fix this issue.
We are using django 1.8.19

**Comment by electrocnic** [comment]
Same problem.

![django-filer-bugs](https://user-images.githubusercontent.com/13003800/51441403-6f25c680-1cd1-11e9-9942-cdda578ab7db.png)

On Ubuntu 18.04, chromium-webbrowser, Django-2.1.5
django-filer: 1.4.3

This is a game-breaking bug. Will have to switch back to normal django file and image models if you don't fix this :'(

**Comment by zypro** [comment]
Same here after upgrading to django-filer==1.6.0 and django==2.2.10
