### ISSUE TITLE
Softlink/alias/shortcut functionality

### ISSUE THREAD

**Issue by tehfink** [django-cms/django-filer#1119]
Apologies if this has already been covered: would it be feasible to implement something like "ln -s" for Files within django-filer? This would result in a similar functionality to Google Drive, e.g.: allowing a File to be present in multiple Folders without requiring multiple copies of it on the filesystem.

**Comment by joshuajonah** [comment]
You can just change the name, "save as new", and then move it to another folder. That makes two "files" with reference to the same image on the drive.

**Comment by tehfink** [comment]
@joshuajonah Thanks for the reply.
I tried to follow your suggestion, but after editing an image's or file's name in Django 1.11.8 & django-filer 1.4.3, I don't see a "Save as new" option, only "Save and continue editing" & "Save".
What exactly is your setup, that allows """two "files" with reference to the same image on the drive."""?

**Comment by joshuajonah** [comment]
Django==1.11.8, django-filer==1.3.2

https://imgur.com/a/HwWfTyH

**Comment by tehfink** [comment]
@benzkji Unfortunately, version [django-filer 1.4.0 removed the 'Save as new' button](https://github.com/divio/django-filer/blob/develop/CHANGELOG.rst#140-2018-11-15), so @joshuajonah's workaround isn't an option anymore.

I'm still interested in having a similar functionality to Google Drive, e.g.: allowing a File to be present in multiple Folders without requiring multiple copies of it on the filesystem.

**Comment by tehfink** [comment]
Would save a lot of file space!
