### ISSUE TITLE
Protect files from being deleted or provide better interfaces when removing files/folders

### ISSUE THREAD

**Issue by FinalAngel** [django-cms/django-filer#1151]
We need a better way to display the impact of deleting files or folders when plugins use filer to reference files, e.g. FilerImageFields.

Normally the references are set to ``on_delete=models. SET_NULL`` on the related model ([see here](https://github.com/divio/djangocms-googlemap/blob/master/djangocms_googlemap/models.py#L232)) which is a better practice than the other options (preventing errors and searching for all plugins first before you can remove a file)

A solution should rather be provided by filer rather than each individual plugin.

**Comment by benzkji** [comment]
normally, the default django delete view shows the impact when deleting. this is not the case with filer?! I tried adding a related_name, with no success?

having a list where files are used is one thing. finding the pages another, as normally, only the plugin is shown...and it could be anywhere...a good solution to these problems is of great value to the UX of filer!

**Comment by benzkji** [comment]
mixing up things. related items are only showing up in delete dialogs when using models.CASCADE, which is, in my oppinion, not the recommended way, as complete contents can be deleted, when deleting just a file. 

so. a new "where is this file used" section, somewhere, would be nice. also, kindof overriding models.SET_NULL, for more strict scenarios, would be nice (could be handled on the delete page?).

**Comment by benzkji** [comment]
related #625
