### ISSUE TITLE
Proposal: Make django-filer easier to configure

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#1170]
Images can have quite a bunch of attributes associated with them. In django-filer these attributes are stored in distinct model fields. This makes it difficult to adopt django-filer for various customer settings. For instance, my current customer requires a URL field to point onto the original source of an image, to comply about copyright information. This of course is something not everybody requires. One solution would be to override the Image model using `FILER_IMAGE_MODEL`. This however requires to swap out the model and creates all sorts of migration problems.

Therefore I would like to propose to use [django-entangled](https://github.com/jrief/django-entangled). By using that library, we could store all attributes inside a JSON-field and edit its content using a form defined by either django-filer, or overridden by the custom project. Moreover, by adding a JSON-field, we would have a storage location to keep all kind of [EXIF tags](https://exiftool.org/TagNames/EXIF.html).

If this proposal is accepted, I will start to implement it.

**Comment by yakky** [comment]
I am all for having a more comprehensive set of metadata stored on the model
I'm more concerned regarding adding another dependency, maybe it might be an optional dependency installable via `extra_requires`?
Do we have a database agnostic jsonfield to use, these days?
