### ISSUE TITLE
Proposal: Add support for the HTML longdesc attribute

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#1172]
Especially for visually disabled users of a website, a textual representation of images can be very helpful. For this reason, the W3C has introduced the special HTML attribute [longdec](https://www.w3.org/TR/WCAG20-TECHS/H45.html). Please don't confuse it with the `longDesc` attribute, which is deprecated.

According to the specs, the `longdesc` attribute shall contain a URL pointing to a resource. The natural way for doing this in Django would be to add an additional field to a Model, and use a view rendering the content of this field. This however is impractical and adds a lot of additional code to each project. I therefore would like to propose the following implementation:

On the form to render the detail view of an image, we add a textarea. Here the user can enter a textual representation for that image. Its content then is stored as a file, side by side with the image, but using the ending `.txt`. This allows the browser to access that file using an URL, very similar to that of the image itself. The element then would be rendered such as:
```html
<img src="/media/filer_public_thumbnails/.../landscape.jpg" longdesc="/media/filer_public/.../landscape.txt" />
```

Since we also have to support multiple languages, we alternatively can store multiple files ending in say `.de.txt`, `.fr.txt`, `.it.txt` and so on. The form then shall provide a textarea for each language provided in `settings.LANGUAGES` using `settings.LANGUAGE_CODE` as default. On rendering that element, a utility function can convert the `request` object into the file which best fits the provided language.

**Comment by yakky** [comment]
I think multilanguage support can be handled externally (for example via django-modeltranslation). we already provide fields that might need translations
I am a bit concerned regarding compatibility and migration path for users which already implemented some kind of multilanguage
Storing external files looks a bit clumsy, as its usage is quite limited, can't we point to a view to serve the content? The expected load should be low enough to have a negligible performance impact versus serving content files

**Comment by jrief** [comment]
> Storing external files looks a bit clumsy, as its usage is quite limited, can't we point to a view to serve the content?

Since the `longdesc` attribute must provide a URL, for me it seems to be straight forward to use the same delivery method as the image itself. Images must be served by the file system, so why not use the same approach to also deliver the description. It anyway is plain text without any HTML tags (to prevent XSS attacks).

> The expected load should be low enough to have a negligible performance impact versus serving content files

That's not the reason I propose this. The problem with a special route pointing to a special view just to serve that content will result in additional maintenance. Since non-blind developers often don't care about that feature, assumingly it easily will be forgotten. By handling it through the file system, it will always be stored side-by-side with the image and served by the webserver rather than the application.

**Comment by yakky** [comment]
I am just a bit worried that images and their respective long desc will not be in sync, for example when moving files between different hosts etc
We can easily return an error if the longdesc data are saved while views are not configured, and for those using canonical URLS views are already configured anyway
