### ISSUE TITLE
Images are uploaded with wrong orientation

### ISSUE THREAD

**Issue by mitar** [django-cms/django-filer#119]
Some images are uploaded with wrong orientation. It seems django-filer does not care about orientation metadata. Probably the problem is in PIL or easy-thumbnails? Probably we have to read this metadata and rotate it ourselves?

http://stackoverflow.com/questions/4228530/pil-thumbnail-is-rotating-my-image

Or is this a bug in easy-thumbnails?

**Comment by lory87** [comment]
Hi @georgema1982 and @mitar Do you still have this issue in current filer version 1.2.0 ? Thank you for your feedback.

**Comment by mitar** [comment]
I have not yet updated to that version, so I do not know at the moment.

**Comment by georgema1982** [comment]
I will look for the image that I had problem with and try it with the latest filter. Will let you know ASAP.

**Comment by alxhghs** [comment]
I am having this issue still on Django-filer 1.2.7. Any updates on how to handle orientation and exif data for images?
