### ISSUE TITLE
Upload success even with 500 internal error

### ISSUE THREAD

**Issue by pupattan** [django-cms/django-filer#1197]
While uploading i am getting 500 internal error. But still the notification on upload window shows "Upload success"

**Comment by pupattan** [comment]
I got the issue, But not sure about the fix
In upload.button.js `responseJSON` actually not providing the Json response from server 
 ```
onComplete: function (id, fileName, responseJSON) {
                var file = responseJSON;
```

**Comment by pupattan** [comment]
This is due to fileuploader.min.js . If its only 200 it sends response to the onComplete function which is in upload.button.js.
**So 500 error will never catch error here**
`if ((this._options.onProgress(id, name, size, size), 200 == xhr.status)) {`

**Comment by jrief** [comment]
Can you please give me a recipe to reproducible this issue.
