### ISSUE TITLE
Filer admin widget "separate" from Django admin

### ISSUE THREAD

**Issue by glaw1300** [django-cms/django-filer#1198]
I've been looking into this for a while, asking questions around other forums to no avail, so I figured here would be a good last-ditch effort to receive feedback. Basically, I'm trying to make an app that allows users to access the django-filer admin widget directly (without having to navigate through the Django admin panel). Additionally, once in the widget, they'd only be able to access a folder owned by them.

I've tried a host of different things to accomplish this and was hoping someone could offer me guidance as to the best way to proceed. Would it be something along the lines of wholly customizing the filer folder template (though that might not stay consistent as filer changes), or is there a better way to accomplish this by simply configuring my urls properly, returning the template to a specific folder in the filer widget based on the user who is active? 

Thanks for the help.

**Comment by davidshumway** [comment]
@glaw1300 Did you ever resolve this issue?

**Comment by derek-adair** [comment]
> is there a better way to accomplish this by simply configuring my urls properly, returning the template to a specific folder in the filer widget based on the user who is active

That's what you should do, in my humble opinion.
