### ISSUE TITLE
support svg files 

### ISSUE THREAD

**Issue by khaldon** [django-cms/django-filer#1205]
I was trying to upload svg type image but it gives me this error 
`Select a valid choice. That choice is not one of the available choices.`

**Comment by jrief** [comment]
This is not yet supported. Before we support this, #1152 and #1162 must be merged.

**Comment by jrief** [comment]
django-filer version 2.1rc1 supports SVG images. Please test.

**Comment by khaldon** [comment]
Thank you so much
