### ISSUE TITLE
Error with mime-type when using dropzone

### ISSUE THREAD

**Issue by peterfarrell** [django-cms/django-filer#1216]
@jrief I have an issue related to #1211 in filer 2.0.2.  When I drop a .ttf file (True Type Font) into a dropzone in the admin (say a filer field on User), I get a browser alert saying:

"localhost:8000 says: test.tff: MIME-Type 'application/octet-stream' does not correspond to file extension of test.ttf."

When I run my file in terminal using mimetypes:

```
import mimetypes
file = 'https://example.com/images/test.ttf'
mt, _ = mimetypes.guess_type(file)
print(mt)
```

Result: `font/ttf`

I'm not sure exactly what is causing this issue for this type of file. Other files like PNG work just fine in the dropzone.

**Comment by jrief** [comment]
Could you please check with your browser's dev tools, which `Content-Type` is used during the request (transfer of `test.ttf`).

If that error remains, I'd probably have to disable the integrity check in django-filer, something I'm reluctant.

**Comment by peterfarrell** [comment]
@jrief When I drop a `.ttf` file in the dropzone, the request header for Chrome is:

`Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryoa8XCQekFdQZoNNX`

Dropping a `.png` file in the same dropzone sends a similar content type.

**Comment by peterfarrell** [comment]
@jrief Forgot to add, the `.ttf` file failed to upload whereas `.png` was fine.

**Comment by jrief** [comment]
@peterfarrell yes, exactly!

**Comment by peterfarrell** [comment]
@yakky @yakky Any progress on a fix for this?

**Comment by jrief** [comment]
Could you please try with this branch: https://github.com/django-cms/django-filer/tree/fix-1216-mime_type
This, in my opinion should fix this bug. If so I will immediately release a new version.

**Comment by peterfarrell** [comment]
@jrief I will try it out when I get into work tomorrow (ET USA tz).

**Comment by peterfarrell** [comment]
@jrief I installed it in our requirements.txt with:

```
-e git+https://github.com/django-cms/django-filer.git@fix-1216-mime_type#egg=django-filer
```

When I drop a TTF file in both Firefox and Chrome:

xxxx.ttf: MIME-Type 'application/octet-stream' does not correspond to file extension of xxx.ttf.

**Comment by jrief** [comment]
Thanks for your feedback, I now added another check to prevent this error.

**Comment by peterfarrell** [comment]
@jrief Tested the newest commit in the branch with the additional check and we no longer received the error. 🥇

**Comment by peterfarrell** [comment]
@jrief just wanted to ping you to see if you know a timeframe on a release for this?
