### ISSUE TITLE
Use Python filetype library to determine the MIME type of a file

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#1217]
As discussed on Slack and approved by @yakky and @macolo, I will change the behavior of django-filer for version 2.1 to use the [filetype](https://pypi.org/project/filetype/) library to determine the MIME-type of an uploaded file.

When uploading through method POST, the Content-Type sent by the browser (via request object) is used to determine the MIME type. When uploading through Ajax, this doesn't work anymore and django-filer uses the file suffix. Moreover, browsers aren't very reliable either, see this [recent post](https://groups.google.com/g/django-developers/c/w7sBZRrQYwE).

**Comment by peterfarrell** [comment]
@jrief Let me know if you need any help testing. I assume this is related to #1216 that I filed?

**Comment by jrief** [comment]
reminder to @jrief : this must be implemented

**Comment by peterfarrell** [comment]
@jrief Has this been merged into a release?
