### ISSUE TITLE
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str()

### ISSUE THREAD

**Issue by ryanstreur** [django-cms/django-filer#1221]
While testing a model which has a filer field, I'm seeing this warning:

```
  .../lib/python3.7/site-packages/filer/utils/files.py:119: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    return slugify_django(unidecode(force_text(string)))
```

The method was changed in #422 in order to support characters like "Ö," so simply changing it back may cause a regression in terms of which characters this method supports.

**Comment by jrief** [comment]
fixed via #1222
