### ISSUE TITLE
Proposal - Improvement ideas

### ISSUE THREAD

**Issue by jbpenrath** [django-cms/django-filer#1225]
## Context

There is an assessment (#1153, #1183) that for some uses where several users have to administrate the same site with different permissions, allowing files to be uploaded into the unsorted folder can be quite a mess.

Based on these assessments and following a meeting with @jrief, I submit the following ideas of improvements:

## Proposal

- [ ] Add possibility to disallow upload into the unsorted folder easily through a setting parameter and disable dropzone in the ImagePlugin if no folder is selected.

- [ ] Display the path where the uploaded files will be saved in the ImagePlugin UI.

- [ ] In the folder tree view, add an "Uploaded at" column.

- [ ] Again in the folder tree view, add the possibility to sort items by name or uploaded date.

The idea of this issue is to debate these proposals and find the best way to improve these points. We will be able to tick off the ideas to implemend as we discuss them.

What do you thing about these proposals?

**Comment by jrief** [comment]
I changed the logic as follows:
Whenever someone uploads a file into a folder, that folder is remembered in its session, so every time the user uploads again, that last folder is used.

Please retry with the upcoming version 2.1rc2 (release date 2021-02-02) or with the current master branch.
