### ISSUE TITLE
2.1rc1 / easy-thumbnails 2.8rc0 : file-unknown.svg

### ISSUE THREAD

**Issue by pcolmant** [django-cms/django-filer#1228]
Hi,

When just installing 2.1rc1 / easy-thumbnails 2.8rc0 on a test venv
Then running collectstatic 
I got : Post-processing 'filer/css/admin_filer.css' failed! 
The file 'filer/icons/file-unknown.svg' could not be found
The file is not in 2.1rc1 django-filer/filer/static/filer/icons/

The file is used in 'filer/css/admin_filer.css' : 
background:#fff url("../icons/file-unknown.svg");

The requirements of my project (python 3.8(.5) ) are : 

asgiref==3.3.1
defusedxml==0.6.0
diff-match-patch==20200713
Django==3.1.4
django-classy-tags==2.0.0
django-cms==3.8.0
django-crispy-forms==1.10.0
django-debug-toolbar==3.1.1
django-easy-select2==1.5.7
*django-filer==2.1rc1*
django-formtools==2.2
django-import-export==2.4.0
django-js-asset==1.2.2
django-mptt==0.11.0
django-mptt-admin==2.0.2
django-parler==2.2
django-polymorphic==3.0.0
django-recurrence==1.10.3
django-reversion==3.0.8
django-sekizai==2.0.0
django-treebeard==4.3.1
djangocms-admin-style==2.0.2
djangocms-attributes-field==2.0.0
djangocms-file==3.0.0
djangocms-link==3.0.0
djangocms-picture==3.0.0
djangocms-text-ckeditor==4.0.0
djangocms-video==3.0.0
djangorestframework==3.12.2
*easy-thumbnails==2.8rc0*
et-xmlfile==1.0.1
html5lib==1.1
jdcal==1.4.1
jsonfield==3.1.0
MarkupPy==1.14
odfpy==1.4.1
openpyxl==3.0.5
Pillow==8.0.1
psycopg2-binary==2.8.6
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
six==1.15.0
sqlparse==0.4.1
tablib==3.0.0
Unidecode==1.1.1
uWSGI==2.0.19.1
webencodings==0.5.1
xlrd==1.2.0
xlwt==1.3.0

I don't get the error with : 

django-filer==2.0.2 
easy-thumbnails==2.7.1

Kr and thanks for this new RC !
Patrick

**Comment by jrief** [comment]
Thanks for reporting.
