### ISSUE TITLE
*.dmg files can't be uploaded

### ISSUE THREAD

**Issue by victor-yunenko** [django-cms/django-filer#1229]
Also it doesn't raise an error in sentry, which is rather odd.

The envirovements:
- python 3.6, djangocms 3.7.4, django-filer 2.0.2
- python 3.9, djangocms 3.8.0, django-filer 2.0.2, [the repository](https://github.com/django-cms/djangocms-template)

**Comment by victor-yunenko** [comment]
As a workaround it's possible to zip them and upload the archive.

**Comment by jrief** [comment]
Just tested with a ~10MB big *.dmg file and everything works as expected.

Please reopen with a stack-trace in case you can reproduce.
