### ISSUE TITLE
Image blocked by adguard (ad blocker)

### ISSUE THREAD

**Issue by ecorreig** [django-cms/django-filer#1233]
We are using django-filer to upload hundreds of images to create tools to show them for psychology based tests, and we now find that some of them (e.g. https://app.projecteorbita.cat/media/public/ad/fd/adfde7ee-abc7-443a-ad3a-de815dba79df/vp-e151.png) are blocked by the ad blocker. 

Following [this ](https://stackoverflow.com/questions/17255493/how-to-stop-adblock-plus-blocking-images-in-html-page) stackoverflow question (and its first response) we believe that it's the combination of public and ad words in the path. 

Therefore, we believe it would be interesting, if possible, to make an exception of directory names to exlude the word "ad".

**Comment by jrief** [comment]
I don't believe that preventing file names starting with "ad", should be part of the django-filers's scope, since the responsibility of not showing them is the ad-blocker. So blame them.
