### ISSUE TITLE
Directory listing template conflicts with djangocms-admin-style sidebar style

### ISSUE THREAD

**Issue by monim67** [django-cms/django-filer#1234]
When we visit folder list view the sidebar CSS breaks as shown in the image below.

**What broke**
- The blue background of the headings are gone. The **Filer** heading in the sidebar is not noticeable as the background has become white.
- The first sidebar menu item "Page Types" has gone under the top navigation bar.

![image](https://user-images.githubusercontent.com/6266677/105044514-05438180-5a91-11eb-95fb-1a36a0fa681e.png)

**Comment by jrief** [comment]
fixed via #1226

**Comment by monim67** [comment]
@jrief the PR does not add the missing `{{ block.super }}` directive. You can see the fix in here in my PR #1235 . Can you confirm if the issue is resolved without the missing directive?

**Comment by jrief** [comment]
Version 2.1rc3 should fix it.
