### ISSUE TITLE
FilerFileField not working 

### ISSUE THREAD

**Issue by justxor** [django-cms/django-filer#1245]
hi , i am trying to use   FilerFileField to drag and drop images

p_pics = FilerImageField(null=True, blank=True,
                           verbose_name="test",on_delete=False)

but my admin looks like https://i.imgur.com/4gHAk6O.jpg

i think there is some problem with static files

**Comment by jrief** [comment]
> i think there is some problem with static files

for sure that is your problem – and completely unrelated to django-filer.
