### ISSUE TITLE
migration 12 fails when files do not exist physically on the server

### ISSUE THREAD

**Issue by sviktorov** [django-cms/django-filer#1249]
Hello, when u support existing projects some times you do not have media folders locally.
Doing the migration 12  of filer causes an error. if its possible following fix to be added in that migration 12

```
def guess_mimetypes(apps, schema_editor):
    FileModel = apps.get_model('filer', 'File')
    for file_obj in FileModel.objects.all():
        try:
            mime_type, _ = mimetypes.guess_type(file_obj.file.url)
        except:
            mime_type = False
            pass
        if mime_type:
            file_obj.mime_type = mime_type
            file_obj.save(update_fields=['mime_type'])
```

**Comment by christine-ho-dev** [comment]
I have the same problem !

`except ValueError` sounds safer but I agree it would be a nice fix.

**Comment by christine-ho-dev** [comment]
It looks like this issue is also mentioned in https://github.com/django-cms/django-filer/issues/1238, which is also still open
