### ISSUE TITLE
Easy Thumbnails 2.8 and django Filer 2.1.2

### ISSUE THREAD

**Issue by pdbethke** [django-cms/django-filer#1265]
Testing filer 2.1.2 out specifically for svg support in djangoCMS 3.9.0 - out of the box I'm not seeing thumbnails for the svg files, which is incredibly helpful in admin "folders" ->folder contents list view. Easy Thumbnails talks about setting a THUMBNAIL_ALIASES var in settings, but it also looks like it works with a template tag - so that would have to be baked into filer beforehand. Am I missing something for out of the box thumbnails for svg files? All migrations ran, etc.

**Comment by pdbethke** [comment]
https://github.com/django-cms/django-filer/blob/c71e4d3de80c08d47f11e879594760aa9ed60a4d/filer/templatetags/filer_admin_tags.py#L65 seems to be the crux of  the issue - looks like thumnailing svg files not supported yet in admin list view?

**Comment by jrief** [comment]
I have no problems to render SVG images in my Django admin list view:

https://user-images.githubusercontent.com/1132472/144883898-d358d7e7-e1fa-40c8-825f-90b4097a464f.mov

**Comment by pdbethke** [comment]
Ok - thanks for the testing! I'll see what's the issue on my side. Possibly an issue with detecting the mime type I wonder. Seems to effect both Chrome and FF so not browser-based.

**Comment by pdbethke** [comment]
Update: I installed the library locally and running some local debugging. It seems as if the images, which are pulled from AWS, are failing the test isinstance(file, BaseImage) (https://github.com/django-cms/django-filer/blob/c71e4d3de80c08d47f11e879594760aa9ed60a4d/filer/templatetags/filer_admin_tags.py#L80)

**Comment by pdbethke** [comment]
Looks like the SVG's read as members of class filer.models.filemodels.File. I do see your example though of it working. Is this a legacy issue - previously uploaded SVG's are tagged as files and instantiated as File not Image (BaseImage) objects?

**Comment by pdbethke** [comment]
Uploading SVG files from my Windows desktop to 2 different instances (one running on heroku and one locally) using a svg clipart (https://freesvg.org/crying-man) gets the following error: in template rendering cannot identify image file <_io.BytesIO object at 0x0000016E75890400> generated by Easy Thumbnails, with the parent exception type being NoSourceGenerator (Tried 2 source generators with no success). I'm attaching the SVG I used. Tried in both Chrome and Firefox. I'm using easy thumbnails 2.8. YMMV but the error pops up with an folder view - meaning it basically borks seeing the contents of any folder. Yeesh. I'd love to blame Windows - I'll try the process on my mac. Maybe some kind of mime upload issue.

**Comment by pdbethke** [comment]
Update: Looks like when you upload a file (or at least when I upload one) the value of poloymorphic_ctype_id is set to 27, whereas it used to be set to 30 - 30 I think being your baseimage class. Manually setting this value back to 30 solves the noSourceGenerator error. So I'm back to thinking that the file uploader sets the polymorphic_ctype_id to 27 in this newer version - which easy thumbnails has trouble processing.

**Comment by jrief** [comment]
The `poloymorphic_ctype_id` is set by Django's initial migration. Also check the [Content-Type framework](https://docs.djangoproject.com/en/4.0/ref/contrib/contenttypes/). If you have a mismatch there, you somehow screwed up your database. Try to reinstall everything and run `./manage migrate` on an empty database.

**Comment by pdbethke** [comment]
Thanks! I'll take a look. I reverted to a pre-migration version of the database, django-filer==2.0.2, Django==3.2.7 and easy-thumbnails==2.7.1 and the error is gone. So somewhere in the upgrade process, migration or otherwise, the error crept in. I did notice the polymorphic id is 27 even in the previous version, so its not that the upgrade changed how thats assigned. It might be a change in Django 3.2.9 as well as that would effect the content type framework possibly. I'll see. Thanks again.

**Comment by pdbethke** [comment]
Jabob - can I ask what storage mechanism you are using for your media assets? I've narrowed the issue down to effecting AWS as easy thumbnails is raising the error "This backend doesn't support absolute paths".

**Comment by pdbethke** [comment]
Hi Jacob - thanks for the quick response. So until that's sorted out, would you recommend downgrading to the version that doesn't encounter the issue with easy-thumbnails and AWS?

**Comment by safaariman** [comment]
I created a PR to fix the issue. The issue is basically S3 accepts the file content as bytes but easy-thumbnails is sending the file content as string. Here is the pull request I created SmileyChris/easy-thumbnails#589.

**Comment by pdbethke** [comment]
@safaariman makes a lot of sense. Thanks for tracking that down. Looking forward to this being merged in to the next release hopefully.
