### ISSUE TITLE
GPL License in dependancies

### ISSUE THREAD

**Issue by omniczech** [django-cms/django-filer#1266]
Hello, I use Django Filer as part of a django cms instance at work and we've been doing an audit of all of our packages for licenses. We noticed that one of the dependancies (Unidecode) is using the GPL and Django Filer is using BSD, which I believe runs against the GPL use terms. There is a functionally quite similar package ([Text-unidecode](https://pypi.org/project/text-unidecode/)) which is very similar in function with the difference that it uses the Artistic License. If a swap can be made I believe it would require minimal effort but help clean up the licensing and avoid issues.

**Comment by jrief** [comment]
Thanks for checking this. I just went over the code and this seems to be a legacy anyway. `unidecode` is only used just before slugifying some strings, which might be in Unicode. Django's `slugify` function nowadays accepts Unicode if we explicitly tell it to do so.

Do you see any problems in removing this dependency and rely on Django's internal handling of Unicode?

**Comment by omniczech** [comment]
That sounds like a fine solution 👍

**Comment by merwok** [comment]
This is not serious.  Bugs don’t stop existing because time passes!
