### ISSUE TITLE
Replaced file in ImageAdmin should reset subject_location

### ISSUE THREAD

**Issue by viliammihalik** [django-cms/django-filer#1275]
Reproduction: 
1. Upload image, for example, 500x500, subject location should be "250,250"
2. Go to the image and upload a smaller image via Advanced>File>Upload for example 100x100. Subject location will stay 250,250 
![image](https://user-images.githubusercontent.com/79649195/152379750-5debef1f-8aa5-410f-9fc1-e9715fce3b88.png)
3. Now if you try to upload another image with dimension let's say 150x150(must be smaller than subject location 250,250). Validation error will be thrown and you need to manually change subject location in input(you can't even change by dragging because the location circle can be outside of the image)

It is not straightforward what to do next when `Subject location is outside of the image` is raised and the user doesn't even use this property.

I propose to reset the subject location if the new image is uploaded via ImageAdmin.

**Comment by jrief** [comment]
Thanks for reporting
