### ISSUE TITLE
Django 4.0 support

### ISSUE THREAD

**Issue by airstrike** [django-cms/django-filer#1279]
Django 4.0 supports Python 3.8, 3.9, and 3.10.  The Django 3.2.x series is the last to support Python 3.6 and 3.7.

**Comment by marksweb** [comment]
That's correct, and python 3.6 reached end of life last year.

**Comment by marksweb** [comment]
@sureshbabupidugu as soon as someone raises a valid PR for it I suppose.

**Comment by marksweb** [comment]
Looks like the tests have dependencies which don't support django 4.

**Comment by pietzschke** [comment]
@marksweb how can i help? I've seen your PR, it seems that the ci needs to be changed?
