### ISSUE TITLE
Choose file popup doesn't select image, it exits with no image selected

### ISSUE THREAD

**Issue by ivandir** [django-cms/django-filer#1317]
Choose file popup doesn't select image with Django 4.1.1. I kept downgrading based on django-filer dependency and the following worked.

Downgrading to 2.2.2 selected Django 4.0.7 - this worked
Upgrading to 2.2.3 and forcing Django 4.0.7 - this worked and one I'm currently using

Don't upgrade to to 2.2.3 and forcing Django 4.1.1 - this is broken

**Comment by rezamazarloo** [comment]
i have the same issue.

**Comment by rezamazarloo** [comment]
in my case the problem does not solve by downgrading.
i think the problem is somewhere else.
i can upload image with drag and drop but the choose file doesn't select any image when i select an image, nothing happens and it seems the image is not selected in django admin.

**Comment by linhvng** [comment]
I'm using Django 4.1.3 and have the same issue. I can upload by drag and drop the image but cannot choose already uploaded files.

**Comment by fsbraun** [comment]
Django filer does not yet support Dango 4.1. can you test if the issue remains if you use this version: `pip install git+https::/GitHub.com/fsbraun/django-filer@feat/django-4-1`?

**Comment by fsbraun** [comment]
@linhvng @rezamazarloo @ivandir Could you check if the latest master branch solves your issue? You can install it using `pip install git+https://github.com/django-cms/django-filer@master#egg=djangocms-filer`. It you be great if #1326 solved your issue!

**Comment by fsbraun** [comment]
@marksweb Should we put this into a minor release?

**Comment by marksweb** [comment]
@fsbraun yeah that sounds sensible to me
