### ISSUE TITLE
I need to upload from Angular JS my images on django filer

### ISSUE THREAD

**Issue by eliezerfot123** [django-cms/django-filer#1329]
Hello everybody!

 I need to upload image files from an Angular js frontend, I've read that it's not possible to use django-filer from outside the admin, but I guess there should be a solution by now. Thanks in advance.

**Comment by jrief** [comment]
No, it's still not possible to upload files from outside into django-filer.

However, you may try [django-formset](https://github.com/jrief/django-formset) and add your own endpoint. Such a feature btw. would be a good project.

**Comment by eliezerfot123** [comment]
Thank you very much, I'll see it
