### ISSUE TITLE
Restrict maximum image dimensions/resolution

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-filer#1330]
With many server instances memory limited, I believe it would be useful to allow for maximum image dimensions to be checked and files rejected if larger.

As the memory usage is not internally checked, it is possible to exhaust the memory available and crash/slow down significantly any other request processing with just a single upload. We have found 6000x6000 pixels to be a safe limit for our case, though this would vary depending on the server resources available.

We have implemented the following monkey-patch to achieve this functionality:

`settings.py`

```
FILER_IMAGE_MAX_WIDTH = 6000
FILER_IMAGE_MAX_HEIGHT = 6000
```

Then we placed a monkey patch into one of our project files:

```
# Monkey-patch filer 2.2.4
import filer
from filer.models import Image
if filer.__version__ != "2.2.4":
    print("ERROR: Expecting filer version 2.2.4")
else: 
    print("Monkey-patching filer Image clean")
    prev_clean = Image.clean

    def clean(self):
        ret = prev_clean(self) # original            
        try:
            imgfile = self.file.file
        except ValueError:
            imgfile = self.file_ptr.file
        imgfile.seek(0)
        if self.mime_type == 'image/svg+xml':
            pass # noop, SVG image
        else:
            from filer.utils.compatibility import PILImage
            from sentry_sdk import capture_exception
            from django.core.exceptions import ValidationError     

            try:
                width, height = PILImage.open(imgfile).size
                print(width, height)
                if width > settings.FILER_IMAGE_MAX_WIDTH:
                    print("Check failed")
                    raise ValidationError({"file": "Image is too wide. Please refresh the tab to continue."})
                if height > settings.FILER_IMAGE_MAX_HEIGHT:
                    print("Check failed")
                    raise ValidationError({"file": "Image is too tall. Please refresh the tab to continue."})
            except ValidationError as ve:
                raise ve
            except Exception as e:
                print(e)            
                capture_exception(e)
                #raise Exception("Unable to process image: {}".format(e))
                raise ValidationError({
                    "file": "Unspecified error {}".format(e)
                })
        imgfile.seek(0)

        return ret
    
    Image.clean = clean # re-assign
```

The above seems to be working fine in the "full" admin view, however, no error is shown when large file is dragged into the file browser popup, nor there is any indication when dragged into the form field directly (the field just re-sets).

To start with though, I believe it would make sense to implement the size check as an option for Filer. Thoughts?

**Comment by jrief** [comment]
I would rather use a setting which already exists in Django, namely [FILE_UPLOAD_MAX_MEMORY_SIZE](https://docs.djangoproject.com/en/4.1/ref/settings/#file-upload-max-memory-size).

**Comment by petrklus** [comment]
> I would rather use a setting which already exists in Django, namely [FILE_UPLOAD_MAX_MEMORY_SIZE](https://docs.djangoproject.com/en/4.1/ref/settings/#file-upload-max-memory-size).

What about image files that are small in size but high in resolution? Yes, there is generally a strong correlation between file size and resolution, however, you can have a pretty small file with huge dimensions.
And when thumbnails are generated, it's the number of pixels that consumers memory.
@jrief do you know what I mean? Let me know please if I am missing anything

**Comment by petrklus** [comment]
Perhaps rather than restricting width/height as I am doing now, it would make more sense to just have a single pixel count limit and check every image upload against it, I just find it easier to explain to editors that they have a certain size square canvas into which all they graphics need to fit in.

**Comment by petrklus** [comment]
Hm, that is not my experience so far - I've checked memory usage with pillow to get size only and it's not loading the images in. That's why my fix is working, I get basically instant file rejection if it has larger dimensions right after the upload completes.
Only once the resize operation starts the image gets left aded.

**Comment by petrklus** [comment]
> Moreover, images with low entropy but many pixels require less memory than images with high entropy but less pixels. For a user usually is easier to determine the size of a file rather than its dimensions.

Also, on this point - do you mean upload file size or memory allocated during thumbnailing? I am not sure the image entropy has much of an impact (if any) on the memory footprint of a resize operation. I have not tested it, just a hunch.

**Comment by petrklus** [comment]
@jrief have you seen, in your experience, the image size query to take up memory? If so, could you please share which platform / pillow version etc.?

**Comment by fsbraun** [comment]
@petrklus I'd appreciate a PR on this. With filer 3.0 file size can be limited. Why not have both limitations (memory size and canvas size)?
