### ISSUE TITLE
Not compatible with django 4

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-filer#1334]
**Packages**
- I've tested django-cms4 with django 4. 
- FYI Django 4.1.7 to be exact!

**Probem**
I stumbled on clicking on a item in the filer does not return in the popup.

**Results**
I've installed django==3.2 and problem is gone.
Even tested django==4.0 but has still the same problem.

**Comment by svandeneertwegh** [comment]
FYI,  i used django-filer==2.2.4

**Comment by fsbraun** [comment]
Solved by #1326
