### ISSUE TITLE
 Missing image icon for dropdown

### ISSUE THREAD

**Issue by renanbgarcia** [django-cms/django-filer#1339]
The only icon missing is the root directory dropdown one on the folders page.

![image](https://user-images.githubusercontent.com/35604644/232646210-bd18f82a-0f36-4e16-9edc-83b4af0a4888.png)

Here you can see the src:
src="/static/filer/icons/breadcrubms_dropdown_28_28.png"

I'm using:
Django==4.2
django-filer==2.2.4

**Comment by RamezIssac** [comment]
Are you using django-jazzmin ? @renanbgarcia
