### ISSUE TITLE
Thumbnail view does not work as expected

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#1343]
That new thumbnail view really looks great, but unfortunately it does not work properly.
@corentinbettiol please check this, because it's a show-stopper for that feature.

## How to reproduce
* Use django-filer version 2.3rc1 or HEAD in branch master.
* Open a directory list view, for instance http://my-site/en/admin/filer/folder/, it should contain at least 1 file or folder.
* Click on the checkbox on the left side of that folder.
* In the toolbar there are buttons to delete, copy and move the selected files. In an additional drop-down menu there are options to change permissions, to rename and to resize the selected images. If at least one file is selected, it is possible to perform these actions.
* Switch over to thumbnail view and try the same. Even if a file is selected, those action buttons are disabled.

Screenshot:
<img width="178" alt="Screenshot 2023-05-10 at 16 24 07" src="https://github.com/django-cms/django-filer/assets/1132472/0841003c-9262-4bc2-b540-d1e5f8f2382b">

**Comment by fsbraun** [comment]
I think there's a solution: #1345
