### ISSUE TITLE
Choose file button is redirecting to admin page

### ISSUE THREAD

**Issue by housUnus** [django-cms/django-filer#1349]
Hi, thanks for the great effort which is so helpful.

I'm using a form for a model with a Filer field of this package, everything works fine on the admin page, but when trying to use the form in a regular manner, the field is rendered on the form with two options **"Choose file"** and "**drop your file here"**, the issue is the "Choose file" buttons is referring to the admin page to select the file even for non-admin users, which creates a security issue for me, 'cause I don't want them to know the admin URL first, and I don't want them to choose the file from the admin panel, I just want them to choose and upload the file from their local storage, 

The ideal case is the field handles that part, on my side I tried to use a custom widget but I faced problems defining the path where to save the files + the file types filtering (.png, .pdf...) which depends on the field declaration.

Regards.

**Comment by housUnus** [comment]
The attached image shows the situation.
``
![issue](https://github.com/django-cms/django-filer/assets/44384710/a78a478f-18d9-4c47-99f9-c88e9cfe938e)

**Comment by housUnus** [comment]
Also when the file is dropped, the file is saved to the last folder a file was added to, which is not a proper behavior, it should save to a default folder path that is specified when creating the field if the upload is not done via the admin panel.

**Comment by marksweb** [comment]
It's been a few years, but I think I remember trying to integrate filer like this and it isn't how it's been built. I think I remember finding out, or coming to the conclusion that the package is only intended to be used from the admin side of things.

Is this the case @jrief @fsbraun?

**Comment by fsbraun** [comment]
PS: Rewriting the widget seems a practical solution to me, but probably will reveal your admin tree in the upload url.

**Comment by housUnus** [comment]
I've dug into the logic behind the saving of the "drag form", I'll try to create and add a file input in the form then when handling the form in my view I'll do the same logic the ajax_upload does, it's the first intuition but I need test it.

**Comment by housUnus** [comment]
Finally, with the help of custom inputs, widgets, and validators, I managed to choose the folder id where to save the file in, a validator to check the file type and other checks, and an additional File input to get the file and upload it once selected with the **ajax_upload** with some changes.
