### ISSUE TITLE
Field verbose_name should use gettext_lazy

### ISSUE THREAD

**Issue by mihalikv** [django-cms/django-filer#1377]
Hi, 
model field verbose_names should use gettext_lazy, because it creates migrations based on user language settings. 

https://github.com/django-cms/django-filer/blob/master/filer/models/foldermodels.py#L9

This is migration generated after upgrade to django-filer 3.0
![image](https://github.com/django-cms/django-filer/assets/10236315/f3cdd97e-dcfe-449b-a928-a574976417da)

Thanks.

**Comment by marksweb** [comment]
@mihalikv No, you're right.

As a general rule;

`gettext_lazy()` should be used for anything loaded at runtime:
* `models.py` (fields, `verbose_name`, `help_text`, function `short_description`);
* `forms.py` (`labels`, `help_text`, `empty_label`);
* `apps.py` (`verbose_name`).

`gettext()`should be used for any modules that are executed during the request process, such as `views.py`
