### ISSUE TITLE
Double .open() causing issues with django-storages 1.14 and S3 backend

### ISSUE THREAD

**Issue by GaretJax** [django-cms/django-filer#1417]
django-storages 1.14 has been released with a bugfix for the `closed` File property: https://github.com/jschneier/django-storages/pull/1249

This causes the code at https://github.com/django-cms/django-filer/blob/master/filer/models/filemodels.py#L257-L260 to raise an [exception](https://github.com/django/django/blob/main/django/core/files/base.py#L114) and thus preventing `_copy_file` from being called.

At this point I'm unsure about what the fix would look like and whether that code is still required. If yes, it might be enough to check for `src_file.closed` before calling the second `.open()`.

**Comment by fsbraun** [comment]
@GaretJax can you share the kind of issues you encountered?

**Comment by fsbraun** [comment]
Fixed in 3.0.6

**Comment by GaretJax** [comment]
Thanks @fsbraun; I somehow did not receive any notification from github for this activity.

**Comment by fsbraun** [comment]
Pleasure. Good catch!!
