### ISSUE TITLE
Uploading SVGs without easy-thumbnails[svg] leaves db in inconsistent state

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-filer#1433]
Without easy-thumbnails[svg] (i.e. reportlab) SVGs are still uploaded/stored as `Image`, but they have width=Null and height=Null stored. To be really consistent, one could store SVGs as `File`, when no support for that image format is available? Or deny SVG upload completly, without support?

Currently, it can be a pain, as one can start a project without knowing this, and ending up with a few hundred svgs in the db, without dimensions.

Dont know what the best solution could be...?

**Comment by benzkji** [comment]
```
from django.core.management import BaseCommand
from filer.models import Image
from easy_thumbnails.VIL import Image as VILImage


class Command(BaseCommand):
    help = (
        "update dimensions of svg images that have no dimensions set, "
        "for whatever reason"
    )

    def handle(self, *args, **options):
        no_dimensions = Image.objects.filter(file__endswith=".svg")
        print(no_dimensions.count())
        for image in no_dimensions:
            if image.width == 0:
                print(image)
                try:
                    imgfile = image.file.file
                except ValueError:
                    imgfile = image.file_ptr.file
                imgfile.seek(0)
                image._width, image._height = VILImage.load(imgfile).size
                image.save()
        return

```
Quickhack, copied some code from filer.  but I get a lot of these errors:
ERROR:root:Unsupported shape type Group for clipping

And dimensions are not updated. And it takes a very long time, for every single SVG. One can argue that my SVGs are too complex or whatever, but these are valid SVGs. I can provide examples if needed?

**Comment by benzkji** [comment]
This issue has probably to be addressed in easy-thumbnails, right?

**Comment by fsbraun** [comment]
@benzkji Can I interest you in creating a PR with that code? I am not sure if that error throws an exception. Maybe just catch the output?

**Comment by benzkji** [comment]
yes. master is the branch to branch off, right?

**Comment by benzkji** [comment]
It doesnt throw an error, but logged 10'000 entries to my Sentry this morning. PR on the way.

**Comment by benzkji** [comment]
#1434

**Comment by jrief** [comment]
No, this is a django-filer issue and has to be addressed here.

**Comment by benzkji** [comment]
@jrief have you seen the PR? Not sure which direction to go.

Also, fixing is one thing, and preventing getting in an inconsistent state is another.

**Comment by fsbraun** [comment]
@benzkji Can we close this issue now that #1434 is merged?

**Comment by benzkji** [comment]
not really sure...as #1434 only does help when things already went wrong...but prevent getting there would be the goal. I don't have a definitive answer, but tend to the "deny uploads" when SVG support is not available? If you decide to not do anything, I'm fine too, feel free to close then ;-)

**Comment by fsbraun** [comment]
Or maybe just turn a SVG into a `File` object as opposed to `Image` object if SVG support is not installed. That's probably easily achievable. If SVG support is added later, however, `File`s will remain `File`s.

**Comment by benzkji** [comment]
Yes, but could lead to other undesired situations (client uploads a few SVGs, then has to re-upload and re-assign everything, when "no SVG support" is detected). I now know about, so...it's just about finding the most accessible solution for people who don't. I would prefer an Image withouth width, and being able to call the managemen command later on.
