### ISSUE TITLE
How to use the django filer file selector in a rich text editor?

### ISSUE THREAD

**Issue by kosuo** [django-cms/django-filer#1439]
Django filer is a great remote image file resource manager. I want to modify all projects to django filer to manage server image resources, but I don't know how to choose to use the django filer file selector from a rich text editor? After consulting a lot of materials, I couldn't find a case where a rich text editor can perfectly integrate with django filer. Is it possible that the django filer file selector cannot be used in conjunction with a rich text editor?

**Comment by jrief** [comment]
In djangocms-text-ckeditor files are uploaded to django-filer. Have a look how it's done there.

If you want to use another RTE you probably have to implement something yourself.

**Comment by corentinbettiol** [comment]
I don't know what you want to do, but [django-ckeditor-filebrowser-filer](https://github.com/nephila/django-ckeditor-filebrowser-filer) uses django-filer to select images and display them in the ckeditor field. You may want to check how it's done here :)
