### ISSUE TITLE
Django-filer styling causes misalignment in the djangocms-image and djangocms-file plugins

### ISSUE THREAD

**Issue by ketaki-udipi** [django-cms/django-filer#1442]
While upgrading to Django 4.2, the image and file upload box is smaller as compared to the Django 3.2 version and thus hides the search and edit icons. Django 4.2 added a class `flex-container` in `django/contrib/admin/templates/admin/includes/fieldset.html`. I think maybe the django-filer styling does not support the flexbox layout correctly.

With Django 3.2:

- Before selecting an image:
![image](https://github.com/django-cms/django-filer/assets/77746894/e44d8b5a-bf82-4eff-8410-6f7bb5eeedf4)

- After selecting an image
![image](https://github.com/django-cms/django-filer/assets/77746894/17f44ec7-65df-4566-ad91-73f747e22e64)

With Django 4.2:

- Before selecting an image:
![image](https://github.com/django-cms/django-filer/assets/77746894/fd65b153-d99d-4366-a32b-61238e6c092a)

- After selecting an image
![image](https://github.com/django-cms/django-filer/assets/77746894/2db32c64-61af-45c5-bf0b-0edbc63cc5c5)

Django version: 4.2
Python version: 3.11
Django-filer version: 3.1.1

**Comment by fsbraun** [comment]
Fixed with #1453
