### ISSUE TITLE
detail_info.html template is incompatible with custom Image models

### ISSUE THREAD

**Issue by W1ldPo1nter** [django-cms/django-filer#1450]
In version 3.1.0, [this hardcoded URL name](https://github.com/django-cms/django-filer/blob/3.1.0/filer/templates/admin/filer/tools/detail_info.html#L14) was added to the `detail_info.html` template. However, the actual URL name is generated like [this](https://github.com/django-cms/django-filer/blob/3.1.0/filer/admin/imageadmin.py#L94), which means that if one replaces the image model (with a name other than `Image`) as described [here](https://django-filer.readthedocs.io/en/latest/extending_filer.html#providing-custom-image-model), the hardcoded URL name in the template no longer matches the actual URL name, leading to reverse errors like this: 
![image](https://github.com/django-cms/django-filer/assets/46226874/87834348-3a9a-4ed3-aaa8-fcf686e69a76)

Django's `admin_urlname` filter could probably be used in the template to generate the URL name dynamically, but would require that the app label part of the URL name is also dynamic (and not hardcoded to "filer").

**Comment by fsbraun** [comment]
@W1ldPo1nter 
What would you think about supplying the expand view url in the context? Would you be interested in creating a PR to fix this?

**Comment by W1ldPo1nter** [comment]
> What would you think about supplying the expand view url in the context?

Sure, that would be another way to solve it.

> Would you be interested in creating a PR to fix this?

I guess I can take a swing at it. I'll try to make some time, can't currently say when I'll get to it though.

**Comment by fsbraun** [comment]
Completed with #1454 and #1471
