### ISSUE TITLE
Removing an images jumps the screen to the top of the page

### ISSUE THREAD

**Issue by marcosguedes** [django-cms/django-filer#1452]
Hi all. The X button on a FilerImageField has an `href="#"` which sends the user to the top of the page when clicked.

![image](https://github.com/django-cms/django-filer/assets/6418368/f3ceae50-2bd5-411d-92bf-d879803c1cad)

I tested this on Django 3, not sure if it happens on others. Quite strange to not see it reported sooner.

The small fix I did was to simply replace `#` with `javascript:void(0);` in [admin_file.html](https://github.com/django-cms/django-filer/blob/b0f39ab39da19bd382cf9975e733dd0b1abe9299/filer/templates/admin/filer/widgets/admin_file.html#L40) which seemed to take care of the problem

```diff
            <a class="filerClearer {% if not object %}hidden{% endif %}" title="{% translate 'Clear' %}"
-                 data-no-icon-file="{% static 'filer/icons/file-unknown.svg' %}" href="#">
+                 data-no-icon-file="{% static 'filer/icons/file-unknown.svg' %}" href="javascript:void(0);">
                <span class="fa fa-close filer-icon filer-icon-remove-selection"></span>
            </a>
```

admin_folder.html should also have the same problem but I haven't tested yet

**Comment by fsbraun** [comment]
Completed with #1453

**Comment by marcosguedes** [comment]
Thank you, perfect, this looks much more clean than my fix
