### ISSUE TITLE
Loaddata results in a FieldDoesNotExist error

### ISSUE THREAD

**Issue by tobyl** [django-cms/django-filer#1455]
When I try to import data via `loaddata` I see an error relating to django-filer:

```
Folder has no field named 'level'
```

If I manually tinker with the JSON file and remove `level`, `lft`, `rght` and `tree_id` keys from the two Folder objects the data loads as expected.

**Comment by fsbraun** [comment]
I would assume you are importing django-filer data exported with a django-filer version below 3 into django-filer version >= 3. 

With django-filer 3 the data structures changed and django-mptt was removed from filer. This also removed the fields `level`, `lft`, `rght`, and `tree_id`. There is no need for replacement. Removing the fields from the JSON therefore should work fine.

**Comment by tobyl** [comment]
Ah, that makes sense.. I thought I had confirmed the versions before posting, but I must have been mistaken - thank you!
