### ISSUE TITLE
PROBLEM IN TEMPLATE (admin_foler.html) WHEN USING 'FilerFolderField'

### ISSUE THREAD

**Issue by martimlello** [django-cms/django-filer#1463]
Hello,
I am working on updating a Django project, which was using version 3.2.6 and consequently used django-filer 2.0.2. django-filer was used so that the user could choose a folder with information relevant to a particular field!!! In the models it was defined like this : 

![imagem_1](https://github.com/django-cms/django-filer/assets/79886837/c77fb229-8927-42ae-96f8-40fa2e6e294b)

And everything worked as expected!

![imagem_2](https://github.com/django-cms/django-filer/assets/79886837/63ba35f2-fa3e-4b94-9fa7-c0fec8b70a58)

In this project update, I updated Django to version 5.0.6 and consequently the django-filer to the latest version, 3.1.1.

When using the same field, I noticed that there are problems with the template, as shown in the image below!!!

![imagem_3](https://github.com/django-cms/django-filer/assets/79886837/b4c9f5a5-b369-4409-a403-61ed8181b781)

I was then able to detect that the problem came from the admin_folder.html file, because when I replaced it with the html from the old version, it already allowed me to see the add folder field...
The current version of the template has the classes hidden, and I can't understand why!

I don't know if I'm missing a setting or something, but I think it's a problem with the template!!!

Your insights into resolving this performance issue would be greatly appreciated.

**Comment by fsbraun** [comment]
@martimlello This is the widget I see when testing (at least within the admin when doing a quick check):
<img width="820" alt="image" src="https://github.com/django-cms/django-filer/assets/16904477/0e0621ca-54c6-43f3-8cca-05da0125b7e8">

Are you using the field within the admin or outside?

**Comment by fsbraun** [comment]
OK, I reproduced the issue with standard Django admin styles. #1467 fixes the issue. 
@martimlello Thanks for reporting this!

**Comment by fsbraun** [comment]
Fixed in django-filer 3.1.3

**Comment by martimlello** [comment]
Thanks @fsbraun  !!! Everything is working perfectly now.

I'd like to make a suggestion, I don't know if it can be in this area, but I hope so :)

You could add something that shows the path of a currently selected folder! 
And also allow that when you click on the folder icon, it allows you to change the currently selected folder, because at the moment I can only change it if I delete it and then add a new one.

![gt](https://github.com/django-cms/django-filer/assets/79886837/f42a9416-3057-407b-969e-cd20e1d32e08)
