### ISSUE TITLE
Moving folders and files with permissions as non superuser takes too long

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-filer#1480]
Superuser click scissor icon (move): Almost immediatly, the move screen appears (dropdown with target folder).

Normal user does the same: It takes ages. Mostly I end up with a "Gateway Timeout". Copying also takes ages.

Does this happen because of permission tests? There are about 100 or 200 folders, an maybe 2000 files in my db, nothing special.

Normal directory listings also take a long time (6 seconds for a list with 79 items).

**Comment by fsbraun** [comment]
Version?

**Comment by benzkji** [comment]
Sorry. Latest, 3.1.3.

**Comment by fsbraun** [comment]
@benzkji Do you have a chance of running a profile, or log the database access?

**Comment by fsbraun** [comment]
@benzkji For testing, I created a branch which caches permissions to avoid recalculation. This right now is just a guess. Would you like to give it a try?

Here's the branch: https://github.com/fsbraun/django-filer/tree/feat/permissions-cache

Please let me know if this is an improvement. Might need some tests, too.

**Comment by benzkji** [comment]
I can test this in August...thanks!!

**Comment by benzkji** [comment]
1:1 comparison on my local machine: your branch is way faster. no more timeouts! thanks!
