### ISSUE TITLE
Add support for Django 5.1

### ISSUE THREAD

**Issue by payamnj** [django-cms/django-filer#1487]
Django releasad minor version 5.1, and the latest version of django-filer is not compatible with this new version.

**Comment by fsbraun** [comment]
Hi @payamnj ! 

django-filer does support django 5.1, but at this point the latest easy-thumbnails release does not. 

@marksweb's  #1476 will remove the pin to `Django<5.1` as soon as easy-thumbnails latest release works with django 5.1. It is currently there as a safeguard.

As for easy-thumbnails, the django 5.1 support (https://github.com/SmileyChris/easy-thumbnails/pull/626) was merged two weeks ago, and I am positive that we'll see a release of this soon. (@SmileyChris: Do you have any ETA?)

Let's not forget, all these repositories are maintained by their contributors for free, mostly in their spare time. Hence I ask you to bear with us.

**Comment by payamnj** [comment]
I see! Thank you very much for the information.

**Comment by MarcoGlauser** [comment]
@fsbraun Judging from the easy-thumbnails changelog, the linked PR was released back in July.
https://github.com/SmileyChris/easy-thumbnails/blob/master/CHANGES.rst
Any chance of removing the <5.1 pin? :)

**Comment by fsbraun** [comment]
@MarcoGlauser Thanks for drawing my attention to the fact that the fix by now has been released. The filer PR is merged and 3.2.2 is out just now: no more pinning to Django<5.1
