### ISSUE TITLE
Uploading bigger SVG files blocks the UI

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-filer#1489]
Users think the system is broken. I've had this issue several times, with architecture projects.

I wonder if the old "create 4 thumbnails for every image right during/after upload" system is still in place? This could be replaced by just creating ONE thumbnail, during rendering of the change list? Thus taking of quite a bit of load, during upload, and making everything a bit more reactive?

**Comment by fsbraun** [comment]
@jrief Do I remember correctly that currently no thumbnails are generated for SVG files?

**Comment by benzkji** [comment]
there is https://github.com/django-cms/django-filer/blob/master/filer/settings.py#L41

I can confirm that I have these 4 sizes on my system. Further, I get a 40x40px version in the changelist, that is generated as well, somewhen.

Without SVG support (ie reportlab), SVGs are `File` objects and don't have a thumbnail.

**Comment by benzkji** [comment]
...so, one could just set `FILER_ADMIN_ICON_SIZES`, to contain only one size. I'll check this, it could reduce processing time a lot. It might still take twice the time as needed (40x40, plus FILER_ADMIN_ICON_SIZES size - one would be enough). If it's already sketchy, twice/half the time is worth a lot ;)

**Comment by fsbraun** [comment]
I'll try to look into this, too. Later though...

**Comment by fsbraun** [comment]
Also, I wonder if "do not create thumbnails upon upload but only upon request" may be the better strategy if and only if there is a separate request for each thumbnail needed:
* Potentially fewer thumbnails created
* Main requests (upload, changelist, ...) do not get blocked

**Comment by fsbraun** [comment]
OK, what I found so far:
* filer creates “thumbnails” for SVG files which are identical to the original and **only differ in the size attributes** (`width` and `height` attribute)
* I'll have to check, but **I doubt it is useful to create those files**. The size can probably be overwritten by an `<img>` tag.
* @benzkji likely **needs thumbnails as rendered PNG/WEBP (bitmap with transparency)** (if the bitmap image size is smaller than the original SVG) to avoid large data transfers and browser rendering times
* I have not confirmed, but I think **the thumbnails created automatically are not those actually needed by the current admin.**

**Comment by benzkji** [comment]
> filer creates “thumbnails” for SVG files which are identical to the original and only differ in the size attributes (width and height attribute)

that is probably true. the issue is the generation of those, as it takes a long time to read xml/svg of large files, with thousands of path elements

> I'll have to check, but I doubt it is useful to create those files. The size can probably be overwritten by an <img> tag.

I guess not, yes. I could live with a version that creates ONE thumbnail. As all thumbnails in filer are quadratic, it would make sense (that is what easy-thumbnail does: modify "viewBox" of the SVG).

> @benzkji likely needs thumbnails as rendered PNG/WEBP (bitmap with transparency) (if the bitmap image size is smaller than the original SVG) to avoid large data transfers and browser rendering times

It's hard to decide, I'm not really sure. Without a crop, we could always use the original SVG. As we did before. But since SVGs are images in filer, it has become different ;) Sure, a few 100'000 path SVGs in the changelist does not make it rendered faster...

> I have not confirmed, but I think the thumbnails created automatically are not those actually needed by the current admin.

That's what I was thinking as well...

**Comment by fsbraun** [comment]
I can imagine not using thumbnails for SVG in the admin, but doing some CSS magic (`object-fit` etc.) instead. This way, **no** thumbnails would need to be created for SVG files unless you use those thumbnails elsewhere.

If you then also had an option to not create thumbnails upon upload (the last point of my previous comment, sort of), you might be fine.

**Comment by benzkji** [comment]
I would be fine with any of these solutions, but would prefer your first, most eleganct one, IMHO. Max image size could be difficult, there are SVGs with binary data (raster images) withing with only a few paths, that are 2mb, etc etc.

By the way, you could also drop the quadratic thumbnails, and use object-fit: contain, to still have a quadrat. I've had many people complain about those - you are not able to distinguish similar image when the change is cropped away ;). But that's another issue.

**Comment by benzkji** [comment]
Will do so, thanks! @fsbraun

**Comment by fsbraun** [comment]
Also, you can try
```
pip install git+https://github.com/fsbraun/django-filer@fix/no-admin-svg-thumbnails
```

This should streamline thumbnails in the admin, and avoid them altogether for SVG files. (Existing thumbnails do not disappear!)

**Comment by benzkji** [comment]
Hi @fsbraun . Thanks. I notice that the change list becomes very very unresponsive, if many big SVGs are listed, this seems unusable, even when not using thumbnails at all (100'000 paths problem). My browser tab required 3gb of RAM!

- render PNG/WEBP for normal thumbnails
- use the original SVG if an SVG is really needed (heavy zoom in, whatever) - without thumbnailer

this is the conclusion, for me. I am not sure if PNGs can be generated from SVGs, though?!

**Comment by benzkji** [comment]
I can confirm that no 8x8/16x16/etc thumbnails are generated, when using the default filer uploading mechanisms.

**Comment by benzkji** [comment]
THUMBNAIL_EXTENSION = "webp"
THUMBNAIL_PRESERVE_EXTENSIONS = ("gif",)

SVGs are still thumbnailed as SVGs. So I guess this would need to be adressed in easy-thumbnails?

**Comment by benzkji** [comment]
I really like the ability to have SVGs in FilerImageFields. But if I knew what it means in a real world, I'm not so sure anymore ;)

**Comment by benzkji** [comment]
I'll probably just deny SVGs bigger than 200kb or so. That's what it was meant for...fair enough. 

The PNG/WEBP thumbnail solution would be nice, but yea, honestly this is a nice to have (and an easy-thumbnails thing).

@fsbraun thanks for all the efforts and investigations. If we get a change list without thumbnailed SVGs, nice, but for me the problem ist "SVG" in general ;). At least we have another setting to deprecate :)

**Comment by fsbraun** [comment]
Just to make sure I understand: The changelist **remains** "very, very unresponsive". It was not more responsive with thumbnailed SVG?

I conclude that we should look into thumbnailing SVG to webp or something (no idea, if that is possible).

**Comment by benzkji** [comment]
Yes, it remains unresponsive in both cases (FF and Chrome on Linux). Thumbnailing only changes the viewBox attribute in the svg, the whole XML needs to be parsed, always.

**Comment by benzkji** [comment]
Fallback: Yes, until we can thumbnail to PNG/WEBP?

**Comment by fsbraun** [comment]
OK, I implemented the fallback: `static/filer/icons/file-picture.svg` is shown if the SVG is larger than 1MB (configurable)

**Comment by benzkji** [comment]
Hero, thanks alot!
