### ISSUE TITLE
Python 3.8 not supported anymore

### ISSUE THREAD

**Issue by defgsus** [django-cms/django-filer#1492]
Hi there, 

a recent commit https://github.com/django-cms/django-filer/commit/01702d8fb78f50638e585a76a8700e8fde0cc050#diff-7121eadf3aeac80b68f4d2107d2192e6b715fd37bafa06a86f04d862ffbe9aa2R69 introduced a `list[int]` type hint (in cache.py:68).

Using an actual python type with brackets requires python 3.10 (or 11, i'm not sure right now). It's certainly not working with python 3.8, which is still listed as minimum supported version for django-filer.

Thank you!

**Comment by Rockyman-star** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by fsbraun** [comment]
@defgsus This is correct. The tests only cover Python 3.10+ and Django 4.2/5.0. The readme needs an update.

**Comment by defgsus** [comment]
Okay, i understand. 

Still, my recommendation is to use `typing.List` and keep the python version compatibility of django-filer 3.1.4
This small type hint is not a necessity to drop compatibility with python 3.8 and 3.9, from my point of view.

Thanks for the quick response :+1:

**Comment by jerch** [comment]
Wouldnt it be better to lift the python 3.10+ requirement by using `typing.List` instead? Please note, that the current LTS of django (4.2) is meant to work with python 3.8

**Comment by marksweb** [comment]
@fsbraun yeah this doesn't seem worth dropping support for two python versions for

**Comment by fsbraun** [comment]
@jerch Can I motivate you to create a PR for this?

**Comment by defgsus** [comment]
@fsbraun yes, i will create it

**Comment by fsbraun** [comment]
@defgsus Will release the update today! What a great turn-around time. Thank you!

**Comment by defgsus** [comment]
Great, thank you @fsbraun . I was thinking about adding py38 to the tests, but i see you just did it. :+1:

**Comment by fsbraun** [comment]
Fixed in release 3.2.1
