### ISSUE TITLE
Editing buttons are cut off in filer field

### ISSUE THREAD

**Issue by krmax44** [django-cms/django-filer#1499]
The Filer File Fields are cut off in CMS editing modals. This seems to be due to absolute positioning of the elements.

![image](https://github.com/user-attachments/assets/90090822-8998-4d3f-a85d-c3447733c438)

When disabling `position: absolute` in the dev tools, it looks like this:

![image](https://github.com/user-attachments/assets/33d326f6-1b66-4ef5-bd05-e152e572f813)

**Comment by fsbraun** [comment]
@krmax44 Thanks for reporting this. What styling are you using for the admin, e.g. plain Django, djangocms-admin-style, or anything else?

Which css file does the `position: absolute` belong to?

**Comment by krmax44** [comment]
Seems to be this one: https://github.com/django-cms/django-filer/blob/735f7280aed82d5e2522e4bef5212280ff144548/filer/private/sass/components/_drag-and-drop.scss#L244-L245

**Comment by fsbraun** [comment]
@krmax44 I think the actual solution will lie elsewhere. Removing the `position` will enlargen the widget. It should fit into the space, however. 

The result should probably look like this: 
<img width="821" alt="image" src="https://github.com/user-attachments/assets/2b09cac6-b6bf-4add-9b95-88ec0aa64936">

**Comment by krmax44** [comment]
I think this should be a flexbox layout, not absolutely positioned. Simply adding `display: flex` to `.filerFile` goes a long way already.
![image](https://github.com/user-attachments/assets/7b4451de-569d-41ea-a5cf-2d241f539d18)

**Comment by fsbraun** [comment]
Yes, that might be an interesting direction to pursue. I think flexbox did not exist when the original css was created...

**Comment by gradel** [comment]
for my setup (custom feincms3 plugin) this css did the trick:
```css
form .form-row .filer-dropzone span.filerFile.js-file-selector > a:first-child {
    padding-top: 0 !important;
    float: left;
}
```

**Comment by aacimov** [comment]
I can confirm the issue as well. When adding video file (.mp4), even worse scenario, the whole `<video>` tag gets embedded and breaks the dropzone container.

<img width="822" alt="Screenshot 2024-11-21 at 09 18 57" src="https://github.com/user-attachments/assets/534d3736-dda7-4c34-832f-2964a1433902">
