### ISSUE TITLE
thumbnail behavior in widget broken - does not disappear on clear

### ISSUE THREAD

**Issue by gradel** [django-cms/django-filer#1505]
Possible bug introduced here:
https://github.com/django-cms/django-filer/commit/f919cbfce877c334ef7b33e329f2749f46fe5876#diff-b4f795d97b769d1875bca80a02e74dd46438e9ebd2a39a818d3999ad8fea0ca3L29
This leads to `detail` becoming True in `file_icon` templatetag and then in `file_icon_context` and `get_aspect_ratio_and_download_url` , where therefore `download_url` gets added to the context what in turn in `file_icon.html` lets the img element get selected  which is lacking the `thumbnail_img` class. The `filer_clear` function
in `addons/widget.js` thus can not find the img: `var thumbnail = container.find('.thumbnail_img');`.

**Comment by cobia** [comment]
I have somewhat similar problems. Needed to override admin_file.html and removed detail=True.

django==4.2.16
django-filer==3.2.3

**Comment by mrbazzan** [comment]
@gradel 
How do I recreate this issue? I would like to give it a try

**Comment by gradel** [comment]
@mrbazzan Just use the current version of django-filer. Then in the admin interface add a image, save the model (page or whatever the ImageField is attached to).
When now clicking the red "clear" X the image doesn't disappear.

![Screenshot from 2024-11-14 00-26-00](https://github.com/user-attachments/assets/019fcfae-fca0-4c12-9932-3baf021c1feb)

@cobia yes, I replaced "detail" with the former '80x80' string.

**Comment by mrbazzan** [comment]
> @mrbazzan Just use the current version of django-filer. Then in the admin interface add a image, save the model (page or whatever the ImageField is attached to). When now clicking the red "clear" X the image doesn't disappear.
> 
I have added an image, saved the model and can still remove the image.
Am I doing something wrong?

> ![Screenshot from 2024-11-14 00-26-00](https://private-user-images.githubusercontent.com/635870/385980348-019fcfae-fca0-4c12-9932-3baf021c1feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzczMTQsIm5iZiI6MTczMTgzNzAxNCwicGF0aCI6Ii82MzU4NzAvMzg1OTgwMzQ4LTAxOWZjZmFlLWZjYTAtNGMxMi05OTMyLTNiYWYwMjFjMWZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwOTUwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWQ2MDA0NDdjNjAxMGIwNGUxY2ExNDVlYjRhNDRhZGZlMTlhYjMzMzA2ZjY2MWMzN2MxODYwMjY4NDQxNWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s0PteKaf004LjgmMINnMDfQDviCW8kea37gtGUkyVjE)
> 
I am unable to view this image.

**Comment by gradel** [comment]
@mrbazzan The issue is not about saving/removing the image from its model. Its just about the javascript driven behavior of the editing interface _before_ saving. As soon as the remove button is clicked the thumbnail used to disappear _immediately_. And as soon as you chose another image a thumbnail of it used to be displayed immediately before any saving of the model.

**Comment by mrbazzan** [comment]
> @mrbazzan The issue is not about saving/removing the image from its model. Its just about the javascript driven behavior of the editing interface **before** saving. As soon as the remove button is clicked the thumbnail used to disappear **immediately**. And as soon as you chose another image a thumbnail of it used to be displayed immediately before any saving of the model.
> 
Now I understand the problem. Thanks. 👍🏿 

> Image is here too:
Thanks for the image

**Comment by mrbazzan** [comment]
This issue can be closed as #1511 fixed it too, right?

**Comment by gradel** [comment]
@mrbazzan: Yes!
