### ISSUE TITLE
Unable to use django-filer from following docs

### ISSUE THREAD

**Issue by mrbazzan** [django-cms/django-filer#1506]
Following this [docs](https://django-filer.readthedocs.io/en/latest/usage.html#filerfilefield-and-filerimagefield) to create `Company` raises `TypeError: ForeignKey.__init__() missing 1 required positional argument: 'on_delete'`

Django: 5.1
django-filer: 3.2.3

Will this be a doc fix to show that `on_delete` is required?

**Comment by fsbraun** [comment]
@sourcery-ai develop
