### ISSUE TITLE
Deleting users results in error.

### ISSUE THREAD

**Issue by kayluhb** [django-cms/django-filer#220]
When I try to delete a user that uploaded images through django filer, I get the following error.

```
'File' object has no attribute 'file_ptr'
```

This is with django 1.3.1 and the latest github version of django filer

**Comment by shatsinn** [comment]
I just stumbled upon the same issue with Django 1.7.4 and django-filer 0.9.9. It seems like the fix was recently removed in 2491771ba024b727b6791b8fa5ccca0266ecca8e by @yakky . Does anyone know the rationale behind it?

**Comment by marcosguedes** [comment]
The same happens with Django 1.4.16

**Comment by nolsto** [comment]
Any news on the rationale for this? Looks like it may have just been forgotten in the big 1.7 commit.

**Comment by yakky** [comment]
I cannot replicate this on Django 1.7 / 1.6
@nolsto @marcosguedes @shatsinn could you please provide steps to reproduce this?
The property has been removed being a hack to support old versions of Django and apparently not needed anymore (actually it prevents Django 1.7 compatibility)

**Comment by shatsinn** [comment]
If my memory doesn't fail me, i ran into it when building a form for users to upload images as FilerImage:

```python
filer_file = FilerImage.objects.get_or_create(original_filename=data.name, folder=folder, file=data, owner=user) 
```
Assigning the owner has been removed and now users can be deleted (with existing users, i looped through all their images and removed the `owner` of those). Not sure if i'll get the time to make a complete isolated example, though.

**Comment by febsn** [comment]
I can reproduce this with a test system:
```
Django==1.7.7
Pillow==3.0.0
Unidecode==0.04.18
argparse==1.2.1
django-filer==0.9.12
django-mptt==0.7.4
django-polymorphic==0.7.2
easy-thumbnails==2.2
wsgiref==0.1.2
```
Steps to reproduce:
* Setup system as above, `INSTALLED_APPS`: only the standard ones + `filer` and `easy_thumbnails`
* Create superuser
* Login in admin as superuser
* Create another user with all `filer` permissions
* Log in with this new account and create a File and an Image instance by uploading a file and an image
* Logging in as the superuser again and trying to delete the other user raises the `AttributeError`.
