### ISSUE TITLE
Undefined Object in Clipboard

### ISSUE THREAD

**Issue by langellightblue** [django-cms/django-filer#257]
Hi, I'm having a problem.
I just installed Django-CMS with django-filer and when I'm upload a file the clipboard says 'undefined undefined'. I watched in the real media directory and the files are really here.
Thanks.

**Comment by Hedde** [comment]
@dlernstrom +1

**Comment by yakky** [comment]
undefined appears for any backend-related issue (file permissions, missing pillow libraries, etc)
