### ISSUE TITLE
"upload_to" for FilerFileField

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-filer#266]
- automatically upload new files into a specific folder in filer (defined by the application using the FilerFileField).
- open this folder by default with the file picker widget

**Comment by mfcovington** [comment]
@stefanfoulis Hi, is there any update about the status of a default/customizable 'upload_to' of a specific FilerFileField? Thanks.

**Comment by k8n** [comment]
Note that #507 already has the code to address this.

**Comment by derek-adair** [comment]
Is there any reason not to configure upload_to as an addon setting?

**Comment by petrklus** [comment]
Is this still a requested feature?
