### ISSUE TITLE
Delete folder

### ISSUE THREAD

**Issue by maximefavier** [django-cms/django-filer#302]
Hi,

I dont't know if it is possible but i haven't found a way to delete a folder i have created. Maybe it is a problem of permission ? On my folder list, i only see a link to update the folder but no link to delete ... It would be useful.

Thanks for your answer,
Max

**Comment by Darex1991** [comment]
i have the same issue.. Super admin no help ;/

**Comment by yakky** [comment]
If using django-suite this is a bug in suit, not really in filer. Please check against a non-styled admin
