### ISSUE TITLE
add a RESTful API

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-filer#324]
for later usage by a new, more ajaxy, admin UI.
The API should be as independent as possible from any global `djangorestframework` settings, since it might be used for other things within a project and django-filer should not get in the way.
- [ ] basic folder and file browsing
- [ ] file upload
- [ ] file moving
- [ ] api pagination (+ throttling?)

**Comment by leesolway** [comment]
Maybe build in support for Django Rest Framework with these options.

**Comment by bhuiyanmobasshir94** [comment]
I have done the rest API for Django filer but I am facing a problem here with folder update when I have to create folder permission as well. Any help will be appreciated.
