### ISSUE TITLE
subject location on alias in settings

### ISSUE THREAD

**Issue by mirzadelic** [django-cms/django-filer#327]
Hi,
i have aliases for thumbnail, and now i need to use subject location with them, how can i do that?

```
THUMBNAIL_ALIASES = {
    '': {
        'cover': {'size': (966, 330), 'replace_alpha': '#fff', 'autocrop': True, 'crop': True, 'upscale': True},
        'category': {'size': (406, 200), 'replace_alpha': '#fff', 'autocrop': True, 'crop': True, 'upscale': True},
        'article': {'size': (230, 120), 'replace_alpha': '#fff', 'autocrop': True, 'crop': True, 'upscale': True},
    }
}
```

**Comment by febsn** [comment]
Sorry for digging this one out. Is there a specific reason why `scale_and_crop_with_subject_location` doesn't automatically use the subject location set in the filer backend? That would make it possible to use the `thumbnail_url` template filter (http://easy-thumbnails.readthedocs.org/en/2.1/usage/#thumbnail-url-filter) together with subject location aware cropping.

**Comment by febsn** [comment]
still relevant.

**Comment by febsn** [comment]
Still relevant, needs a little design decision (Should `scale_and_crop_with_subject_location` use the default subject location saved in the database?)
