### ISSUE TITLE
Feature request: Front-end upload widget

### ISSUE THREAD

**Issue by affan2** [django-cms/django-filer#341]
I can see this mentioned as part of the ToDo - any chance there's an alpha / beta version available yet?

**Comment by mabuelhagag** [comment]
+1

**Comment by qcaron** [comment]
+1

Anyone managed to make it work?

**Comment by frague59** [comment]
+1

**Comment by blackboxx** [comment]
+2

**Comment by mezitax** [comment]
+1

**Comment by jrief** [comment]
I could implement that into **django-filer**.
One of my requirements is that the underlying JavaScript library *must* not have any dependency to any framework, such as jQuery, etc. For [AngularJS I already implemented that feature](https://django-angular.awesto.com/image_and_file_upload/), which does not meet that criteria.

A popular library requiring only native JS is https://www.dropzonejs.com/ . There is also an interesting article on [Smashing Magazine](https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/) on how to implement that feature without any library at all.
Any other proposals?

As usual, the biggest problem for such a feature request, is funding. If enough readers of this issue are willing to fund it, I will setup a Kickstarter project. So please share your intentions.
