### ISSUE TITLE
Encoding error when copying folders with non-ascii characters

### ISSUE THREAD

**Issue by bikeshedder** [django-cms/django-filer#422]
Simply create a folder like "Schöne Bilder" and try to copy it.

After having a look at the code I found several lines where `force_str` was being used. I think all those should be replaced by `force_text`.

For this issue to fix it is sufficient to change one call to `force_str` to `force_text`: https://github.com/bikeshedder/django-filer/commit/f901f085ca4ab16ed52e3c4805ed5022e85e8793

After having a look at the other points where `force_str` is used I think they should all be changed to `force_text` as I don't see why bytestrings should be used for folder and file names at all.

**Comment by jrief** [comment]
I will fix this. I already did it for django-cms and djangocms-text-ckeditor.
