### ISSUE TITLE
Reducing django-filer database queries 

### ISSUE THREAD

**Issue by heyscam** [django-cms/django-filer#426]
Hi there,

Is there any way to reduce the number of DB calls made by filer? I'm iterating over objects that each have a filer image and each one produces a DB hit. I've tried select_related and prefetch_related but can't get anything to reduce the count in debug toolbar. Any advice much appreciated! Thanks.

**Comment by bldm95** [comment]
In my app, I have a model:

`class ImageModelProduct(models.Model):
    image = FilerImageField(
        related_name="model_product_images",
        on_delete=models.PROTECT,
    )
    model_product = models.ForeignKey(
        ModelProduct, on_delete=models.PROTECT, related_name="images"
    )`
I'm using prefetch:
`.prefetch_related("images", "images__image")`

**Comment by bashu** [comment]
@bldm95 this doesn't work for admin inlines

**Comment by bashu** [comment]
@heyscam did you find solution?

**Comment by hypy13** [comment]
filer_image_file

 its the relation name for images
forexample i use photo__filer_image_file
