### ISSUE TITLE
ProgrammingError: relation "filer_image" does not exist

### ISSUE THREAD

**Issue by ekarious** [django-cms/django-filer#427]
Hello !

When tying to use coverage for testing purpose, i encountered an error.

```
ProgrammingError: relation "filer_image" does not exist
```

With more details : 

```
FATAL ERROR - The following SQL query failed: ALTER TABLE "blog_imagearticle"
ADD CONSTRAINT "image_file_id_refs_file_ptr_id_d5d53edf" FOREIGN KEY
("image_file_id") REFERENCES "filer_image" ("file_ptr_id") DEFERRABLE INITIALLY 
DEFERRED;
```

The error was: relation "filer_image" does not exist

I though about it but i don't really know how to fix this error. Does some of you encountered this problem too ?

I'm have, in a lot of plugins : 
- django 1.6
- django-suit 0.2.9
- django-filer 0.9.5

**Comment by linevich** [comment]
Hi @yakky. I have the similar issue:
All works perfectly when I run `manage.py makemigrations && migrate ` on clean database, but if I run `manage.py test` it says: 

```
django.db.utils.ProgrammingError: relation "filer_image" does not exist
```

- Django == 1.9.4
- django-filer == 1.1.1

Installed apps:

```
INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'easy_thumbnails',
    'filer',
    'mptt',
    'cmsplugin_cascade',
    'cmsplugin_cascade.extra_fields',
    'cmsplugin_cascade.sharable',
    'cms',  # django CMS itself
    'treebeard',
    'adminsortable2',
    'menus',
    'sekizai',
    'bootstrap3',
    'solo',
    'meta',
    'meta_mixin',
    'djangocms_inherit',
    'djangocms_file',
    'djangocms_link',
    'djangocms_text_ckeditor',
    'djangocms_page_meta',
    'landing',
    'portfolio',
    'order_form',
)
```

**Comment by yakky** [comment]
Which filer and polymorphic version are you using?

**Comment by linevich** [comment]
@yakky 

- filer == 1.1.1
- polymorphic == 0.9.1

**Comment by stefanfoulis** [comment]
Since Django 1.7 migration dependencies are evaluated automatically. But maybe something went wrong with the migrations depending on django-filer: https://docs.djangoproject.com/en/1.9/topics/migrations/#dependencies

**Comment by linevich** [comment]
Looks like it's django tests bug, because when I run tests with Pycharm Test runner I have issues with other apps, [without migrations](https://pypi.python.org/pypi/django-test-without-migrations/) everything works fine.

**Comment by tdsymonds** [comment]
@yakky @linevich did you ever manage to get this working? I've recently created a new project and have no problem with migrations but when I'm running ./manage test I get the same error.

I'm using:
Python 3.4
Django == 1.9.9
filer == 1.2.5
polymorphic == 1.0.1

I have a similar setup on another project with Python 2 and haven't encountered the same problem if that helps at all?!

**Comment by tdsymonds** [comment]
Ok so I managed to resolve my problem. The problem was with the cmsplugin-filer (https://github.com/divio/cmsplugin-filer) package as opposed to this one. I had to explicitly run the makemigrations command for each of the apps:

```
./manage.py migrate cmsplugin_filer_image
 ./manage.py makemigrations cmsplugin_filer_file
...
```

And then the tests worked.
