### ISSUE TITLE
Switch to django-treebeard

### ISSUE THREAD

**Issue by yakky** [django-cms/django-filer#483]
To make filer consistent with django CMS it should be ported to treebeard to avoid duplicating dependencies when used with django CMS

A 3.0 compatility branch should be maintained

**Comment by SalahAdDin** [comment]
Algo wagtail cms, it uses treebeard.

**Comment by gannettchad** [comment]
:+1:

**Comment by philippeowagner** [comment]
:+1:

**Comment by driesdesmet** [comment]
:+1:
