### ISSUE TITLE
Get mimetype/content_type of file

### ISSUE THREAD

**Issue by kelvan** [django-cms/django-filer#505]
I can't find any possibility to get the mimetype of a MultiStorageFieldFile, but this information would be very handy.
For example displaying an audio icon for audio files by simple checking mimetype instead of extension.

**Comment by yakky** [comment]
Actually filer encourages a more abstract approach to file types; see http://django-filer.readthedocs.org/en/latest/extending_filer.html for more information
Basically you a create a class for each file class (which may include more than one mime type) and the get the icons and filters on those type "for free"
