### ISSUE TITLE
AttributeError when opening 'unfiled files'

### ISSUE THREAD

**Issue by rprader** [django-cms/django-filer#527]
When I try to open the 'unfiled files', I get the following error:

```
AttributeError at /de/admin/filer/folder/unfiled_images/

'Options' object has no attribute 'module_name'
```

I'm using the newest django version 1.8.1 with the newest version of django-filer 0.9.9

**Comment by lory87** [comment]
gentle ping @rprader Do you still have this issue with current filer version 1.2.0 ?
