### ISSUE TITLE
Problems with filenames containing non-ASCII characters

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#574]
Uploading files which contain non-ASCII characters, for instance German Umlauts, currently is not possible.

**Comment by yakky** [comment]
@jrief I tested this on a plain filer installation upload a file named "Zauberflöte ita.docx" with no issues
Could you provide more context?

**Comment by stefanfoulis** [comment]
we currently use unidecode to turn any special chars into ascii chars: https://github.com/stefanfoulis/django-filer/blob/develop/filer/utils/files.py#L105

@jrief do you mean that the umlauts are not preserved (IMHO not a bug) or that the upload completely fails?

**Comment by lory87** [comment]
gentle ping @jrief Do you still have this problem with current filer version 1.2.0 ? Thank you for your feedback.
