### ISSUE TITLE
Filer and Grappelli

### ISSUE THREAD

**Issue by C9t0** [django-cms/django-filer#576]
Hi there,

I have try to use Filer in combination with the Grappelli Admin Menu and got some tamplating issues.
- No Bottons - the /static/admin/css/base.css is missing, so there would no bottons. 
- Double Object Tools - I dont no why but the block object-tools from the directory_listing would be renderd twice
- No SideBar - Instead of the normal contailer/content div hierarchy there is no a grp-container/grp-content/grp-content/container hierachy so sidebar would be displayed out of the window

**Comment by jakob-o** [comment]
+1

**Comment by OktarinTentakel** [comment]
+1

**Comment by ad-m** [comment]
+1

**Comment by lory87** [comment]
gentle ping @jakob-o, @C9t0, @OktarinTentakel and @ad-m Do you still have this problem with current 1.2.0 filer version? Thanks for your feebdack

**Comment by wwarne** [comment]
@lory87 I've got filer 1.2.0 and grappelli 2.8.1.

The div element with class "navigator-tools" (it has Delete, Copy, Move buttons in it) is doubled f
or some reason. I can't understand why. I tried to fix it yesterday but failed.
![2016-04-30_140617](https://cloud.githubusercontent.com/assets/2045176/14935511/d34f5384-0edc-11e6-8843-fd6f56ba4076.jpg)
Everything else seemes ok to me.

**Comment by lory87** [comment]
Hi @wwarne 
We will have a look and let you know when we could reproduce and fix the issue.

**Comment by amartinaccor** [comment]
+1. The problem lies in `django-filer/filer/templates/admin/filer/folder/directory_listing.html`, line 183. The `content` block defines an `object-tools` block. The content of this block is also used by grappelli (in the sidebar, I guess). Renaming this block to something else solves the issue. I don't know however if doing this breaks something else.

**Comment by general03** [comment]
+1 I have the same issue
> Double Object Tools - I dont no why but the block object-tools from the directory_listing would be renderd twice

**Comment by haloween** [comment]
+1 BUMP

**Comment by general03** [comment]
> I added some CSS to fix things but +1

Can you put your CSS here

**Comment by bashu** [comment]
5 years later...

**Comment by jrief** [comment]
If you want to extend the layout of django-filer, you are free to add whatever CSS you like. It is not the responsibility of the maintainers of django-filer to add CSS for other skins of Django. Besides Grapelli there are a bunch of alternatives, such as django-suit, django-admin-style, jet-admin, etc.
