### ISSUE TITLE
Exif data failing for private files

### ISSUE THREAD

**Issue by Julien-Blanc** [django-cms/django-filer#599]
Cannot get exif data for private files, because in pil_exif.py, only default storage is used. This result to a file not found exception for private files. A way to trigger this is to put a private image inside a cmsplugins_cascade carousel.

Fixing get_exif_for_file in the following way :

``` python
    def get_exif_for_file(file_obj):
        if file_obj.storage:
            im = Image.open(file_obj.storage.open(file_obj.name), 'r')
        else:
            im = Image.open(storage.open(file_obj.name), 'r')
        return get_exif(im)
```

makes it work (not sure if the test for file_obj.storage is really needed).

**Comment by rhunwicks** [comment]
Even `Image.open(file_obj.storage.open(file_obj.name), 'r')` will fail for non-file storage systems. For example, I am using https://github.com/chrisspen/django-database-files-3000/tree/master/database_files, which saves the file into the database. At the point that `get_exif_for_file` runs, the save isn't complete, and so it isn't in the database. Similarly, the upload hasn't finished so it doesn't exist with its final name in `/media`. In fact, at this stage it is a file on disk called (say) `/tmp/tmpbbopecfa.upload`. In theory (for a small image) it could be just in memory.

Therefore, the storage can't open it at all - neither the real (`backenddatabase_files.storage.DatabaseStorage`) nor the Django default one.

But on the other hand the file object provided by Django already implements the `read`, `seek`, and `tell` methods required by PIL to create the image.

Therefore, I think that it should work just fine with:

```python
def get_exif_for_file(file_obj):
    im = Image.open(file_obj, 'r')
    return get_exif(im)
```

Note that this is same way it works in `filer.models.abstract.BaseImage.save()`:

```python
self._width, self._height = PILImage.open(self.file).size
```
