### ISSUE TITLE
Proposal: Show where a file/folder is used

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-filer#625]
List view: have a column "usage", that is either "-" or "5x" or "99x".
Detail view: show every instance the file/folder is linked to. Somewhere in/below the form

what do you think?

**Comment by benzkji** [comment]
Still sounds like a cool feature? Doesn't it @stalebot ;-)

**Comment by benzkji** [comment]
Current implementation in django-folderless: https://github.com/bnzk/django-folderless/blob/develop/folderless/models.py#L142

Only drawback: Requires `related_name` of the file/image field not to be `"+"`

**Comment by marksweb** [comment]
@benzkji This sounds useful. Could you put a PR together?

**Comment by benzkji** [comment]
indeed useful, but @stalebot is extremly stressful ;-)
