### ISSUE TITLE
get_exif_for_file does not close file

### ISSUE THREAD

**Issue by wiebren** [django-cms/django-filer#660]
get_exif_for_file in utils.pil_exif does not close the Image file, leading to "Too many open files" errors when reading a lot of files.

Possible fix:

``` python
def get_exif_for_file(file_obj):
    with Image.open(storage.open(file_obj.name), 'r') as im:
        return get_exif(im)
```

**Comment by rhunwicks** [comment]
When I implemented something similar to this, I had errors.

I was trying:

```python
def get_exif_for_file(file_obj):
    with file_obj as f:
        im = Image.open(f, 'r')
        return get_exif(im)
```

But then I found that when we got to `filer.models.abstract.BaseImage.save()` it does:

```python
self.file.seek(0)
```

And that raised `ValueError: I/O operation on closed file.`
