### ISSUE TITLE
Proposal: Better images preview in select list

### ISSUE THREAD

**Issue by Neuronus** [django-cms/django-filer#723]
It'll be great, if filer provide config to set image preview size in lists - or, mouse hover thumbnails feature. 

Now it's very hard to choose image - image thumb in list is absolutely too small - and change it is hard (simple replace of size in template tag is not enough - it need rebuild tables structure)

**Comment by jeeschr** [comment]
Should be possible with some CSS changes

**Comment by Neuronus** [comment]
Nope, you cant just change CSS - HTML table is hardcoded in template etc.

**Comment by macolo** [comment]
Agreed, the image id downscaled to ~50px.

The dimensions can be increased through CSS to these 50px without quality losses - but that's not really sufficient.

I think what's needed is more a Wordpress-media-like tiles mode instead of just bigger thumbnails.
