### ISSUE TITLE
'File' object has no attribute '_committed'

### ISSUE THREAD

**Issue by techscientist** [django-cms/django-filer#739]
I am getting this error when trying to point an existing file to a FilerFileField of a model: 

'File' object has no attribute '_committed'

```
`file, created = File.objects.get_or_create(owner=instance.issued_by, description=desc, name=filename, is_public=False, file=File(open(filename)))

    l.info("Created %s file? %s" % (file.path, created))

    instance.generated_doc = file
    instance.save()
    l.info("Done!")`
```

Can you please tell me how to programmatically save an existing file to the FilerFileField of the model?

**Comment by joshuajonah** [comment]
I would start with posting all the code. Are you using `filer.models.filemodels.File`?

**Comment by psychok7** [comment]
Thanks, i was able to glue this together and make it work:

```python
        from django.core.files import File as DjangoFile

        file_obj = DjangoFile(open(filename, mode='rb'), name=f'{instance.id}.csv')

        obj, created = File.objects.get_or_create(
            original_filename=file_obj.name, file=file_obj, folder=folder,
            is_public=True, description='CSV'
        )

        instance.generated_csv = obj
        instance.save()
```

**Comment by Olfredos6** [comment]
@psychok7 how do I proceed when saving multiple files inside a FileField?

**Comment by psychok7** [comment]
@Olfredos6 I don't think you can. I filefield only has 1 file. You can probably group everything under the same parent folder or use a many to many to achieve the same.

**Comment by galilea-g** [comment]
This work for me
```
from django.core.files import File as DjangoFile
file_obj = DjangoFile(open('C:/Users/test/Desktop/files/PDF.pdf', mode='rb'),name='PDF'])
arc = Test.objects.create(
   files = file_obj,
)
```

**Comment by HarshNarayanJha** [comment]
Hi there,
I had also similar error, but on the ImageField.

I tried to make my blogpost's modal thumbnail optional by typing null and blank True. Than i created a checkbox in forms.py and in the views.py I did the following

Views.py
post = Post()
if not form.cleaned_data["the_checkbox']:
    tumbnail = form.cleaned_data["thumbnail_file"]
else:
    print("not a thumbnail")

#all other stuff here, username, subject etc
if not form.cleaned_data["the_checkbox']:
    post.thumbnail = thumbnail

post.save()

#end
Yes, I checked if the form.is_valid() and migrated my modals. Same worked for the profile picture,
But in this, it is giving me error
**ImageField has no attribute "_commited"**

The error arises from the post.save() line and in pre_save() method of modal

Please help me if there's anything that i don't know
THANKS

**Comment by Jay-davisphem** [comment]
Abeg this is not solved yet

**Comment by haasr** [comment]
Not sure if this helps, but you can trick Django into treating a bytes stream as a file. I use this when I want to write new files into AWS S3., e.g.,

```
from io import BytesIO
from django.core.files.base import File
from .models import *


class StreamWrapper(BytesIO):
    _committed = False # Django checks for this flag when creating a File

csv_string = "col1,col2,\n\"row1,col1\",\"row1,col2\"\n\"row2,col1\",\"row2,col2\""

stream = StreamWrapper(csv_string.encode('utf-8'))
file_name = now.strftime("somefilename.csv")
file = File(name=file_name, file=stream)

upload = S3LogfileUpload(file=file) # Custom model that takes Django file
upload.save()

```
