### ISSUE TITLE
Can't edit 'unfiled files' even though permissions granted

### ISSUE THREAD

**Issue by jsma** [django-cms/django-filer#741]
The permissions check [here](https://github.com/divio/django-filer/blob/3c1cf697cd1d4d179fd5278a10e1bd3bcc44ff4f/filer/models/filemodels.py#L203-L218) always returns False if a user does not own an 'unfiled file' no matter what permissions are explicitly granted to the user.

I've created a non-superuser 'CMS editors' group and assigned all standard available filer permissions, but this check prevents them from editing any unfiled files they don't own. Even if I enable FILER_ENABLE_PERMISSIONS and grant all permissions to all items to this group, this is not checked if the file does not have a folder. 
<img width="441" alt="screen shot 2016-02-18 at 7 44 20 pm" src="https://cloud.githubusercontent.com/assets/24574/13166033/27a5544e-d678-11e5-973b-982fad98de10.png">

**Comment by stefanfoulis** [comment]
By design permissions only work on folders or ownership. We'd have to add a new special permission for the ``unfiled files`` folder to allow non superusers to edit not owned files.

Tangentially related: There is an unfinished and outdated branch that implements file level permissions: https://github.com/divio/django-filer/pull/361

**Comment by stefanfoulis** [comment]
ah... think before you post! Sorry, that permission already signifies "all folders", so we could count "unfiled files" as one of "all folders" and just change the permission check. No need for a new permission.

**Comment by jsma** [comment]
As a workaround, I created a 'General' folder and moved all unfiled files there. It appears that with the new/upgraded UI (the site was originally built with django-filer < 1.0.6), users can't upload unfiled files any longer, they must always be within a folder first. So this shouldn't be an issue going forward for us.

Not clear what the 'proper' fix is for django-filer. It does seem like the explicit permission for 'all items' should work as advertised. But in general (and especially for those not using the advanced permissions system), perhaps there should be an upgrade note to move unfiled files to a folder?

**Comment by stefanfoulis** [comment]
We also allow direct uploading of files by dragging it on the widget of a FilerFileField. I think that in that case it'll still end up in "unfiled files". Lets keep this issue open to address that problem.
@jsma thanks for the report and tests!

**Comment by jsma** [comment]
Yes, I saw that and meant to reply earlier to ask some conceptual questions but soooo busy...(copied and pasted from my draft Github ticket I never filed):

The current interface is inconsistent in how 'unfiled files' works. If clicking an 'Upload Files' button or attempting to move a file, the user **must** select a folder as the destination. 

If a user drags and drops a file onto the 'root' view, *or* if they use the CMS filer plugin, the uploaded file *only* goes to the unfiled files section.

I'm speaking in ignorance of the internals of the code, history of the project, known use cases, etc. but it seems like 'unfiled files' should either be turned into a proper folder, or deprecate it and require users to specify folder destinations for all files whether they are uploaded via drag and drop or via 'Upload files' form. Thoughts?

**Comment by stefanfoulis** [comment]
@jsma Ah, making it a real folder sounds like a splendid idea. Then you can set permissions for it individually, if you want. And it would also be covered with the blanket "access to all folders" permission.

**Comment by pjk5** [comment]
Anything new on this?

We are maintaining an intranet website which uses filer permissions and secure storage backend to prevent access of files for unauthorized users. However files in unfiled files / unsorted uploads are not accessible for non-superusers. This continually causes problems when files end up to this "folder" using drag and drop etc. At the moment files have to be manually moved to a custom default folder whenever some non-superuser reports files not being accessible.

**Comment by stefanfoulis** [comment]
@czpython @mkoistinen what do you guys think about the "making 'unfiled files' a Folder" idea?

**Comment by czpython** [comment]
@stefanfoulis 
I think it's a good idea but from a user perspective is it ok for files from all users to land there?
Should we provide one folder per user (created only on first upload)?

**Comment by clearf** [comment]
Hi All,
It seems like this is still a problem, is that correct? Just spent a bit debugging this and came across this open issue.

Thanks,
Chris

**Comment by wfehr** [comment]
Came across this as well, any news so far?
