### ISSUE TITLE
fix or re-design custom image functionality

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-filer#778]
django-filer used to have the ability to replace the `Image` model with a custom model (similar to how `Django` allows replacing the `auth.User` model).

New unit-tests have shown that this functionality broke somewhere along the way and  that it does not work in some places.

We should either fix it. Or possibly scrap it and re-design the feature in a more generic way. It would be nicer if we'd not hack in the model (with all the negative migration related issues). Instead allow just adding additional custom File types models for whatever (Video, Document, alternate Image, ...) and hiding ones you're not interested in (e.g hide `Image` if you add your own altered `Image`).

Some things that need refactoring for the new implementation to work:
- a registry where the the different file types can be added
- file types must be able to claim file extensions, so that the uploader can hand newly uploaded files to them for processing
- FilerImageField needs re-thinking, since it currently produces a ForeignKey directly to the Image model. In should be deprecated in favour of a more powerful FilerFileField that can cover the needs of FilerImageField and other file types.

**Comment by lory87** [comment]
@stefanfoulis Is this issue fixed with #772?

**Comment by stefanfoulis** [comment]
@lory87 no, this is unrelated to #772
