### ISSUE TITLE
First impressions - how do I disable most of the UI?

### ISSUE THREAD

**Issue by andybak** [django-cms/django-filer#835]
(Please take this in the spirit that it is intended. I've skimmed the docs and installed django-filer in a project where I'm looking for a replacement for Django FIlebrowser. I always think it's valuable to share first impressions - even if they later turn out to be misinformed)

So installation was a breeze. Having to specify a unique related name is a minor pain and it can probably be abstracted away - you could use <app_label>_<model_name>_<field_name> but allow overriding?

Anyway - that's minor. My aim is a simple, user-friendly image field for a staff-facing admin. My users are my clients and their staff. I'm using Django 1.8 but with the flat admin from 1.9.

First thought about the admin widget - it's takes up a _lot_ of screen space and putting it on the same row as other fields isn't going to work: ('name', 'logo', 'photo',), It doesn't blend with the other widgets and rather takes over the screen. I'll probably want to fix that with CSS or by overriding the widget markup.

Labelling the main button 'upload images' is confusing as clicking this is also how you browse for already uploaded images. You either need separate 'browse' and 'upload' buttons or find a more general label for this button.

Having a default folder called 'unsorted uploads' implies there is a way to sort uploads? I couldn't see any way to move files to new folders. It's also confusing as it appears to be a subfolder of 'root' but then it seems to BE the root directory. You usually don't see a folder icon for the folder you're in. It probably looks more intuitive when there are more folders but the initial view is confusing.

Furthermore - when I click into the folder - I lose the drop target. So the way I would expect to upload files into this folder (navigate into it then upload) doesn't work. Again - once I added a new folder it made a bit more sense but UX first impressions are fairly important. Possibly - making 'unsorted uploads' look less like it's a normal folder and this might be less perplexing. It's not really a folder - unless you regard it as the root folder?

So I added a folder and uploaded a file. The 'edit image details' screen is interesting but I immediately switch to the docs to see how I can override it. You see - it has way too much on it. Every field means time spent explaining to the user what that's for and from a brief glance I would only need to expose a single field to my users in most cases - alt tag (and half of them never use that). Sometimes title will be useful but not in every case. Filesize and dimensions are useful but nearly everything else is just going to clutter the screen and confuse my users. It's great having them there for the times I need them but I'd really like the docs to explain quickly and simply how to hide them and present the fewest possible options.

I hope this is helpful. I understand my requirements (mainly for maximum UX simplicity) might different to yours but hopefully they are not uncommon goals and sharing my initial thoughts is of some use.

**Comment by benzkji** [comment]
Interesting (and mostly valid, IMHO) points. I also have a couple of them ;-). My main concern is, that filer more or less is styled like django-admin-tools, but should more align to django defaults, when these are not installed.

The "edit image details" is overblown, that's true, but most clients never land there ;-) You forgot the "Subject Location", which can be a really great tool! But yea, why not "alt text" and "replace file" fields, and that's it.

Thinking further, one could implement a "FILER_USE_REDUCED_UI" setting, and then really strip down widget and admin. Some time ago (2010) we used a custom "filer_enhanced" (haha) module, that did some of these things, but, maintainance, ...etc...

**Comment by benzkji** [comment]
still an issue for us. But things got a little better, at least filer now works with plain normal django (withou djangocms-admin-styles).
