### ISSUE TITLE
CSS Issue in admin pages

### ISSUE THREAD

**Issue by SteinRobert** [django-cms/django-filer#840]
We are currently working with `django-filer 1.2.0`. There is an issue with the styling somehow I guess. I did not examine it very well, maybe you have a quick idea what's the matter here?

![screenshot from 2016-05-03 20-30-43](https://cloud.githubusercontent.com/assets/1231105/14994145/8e0b04dc-116e-11e6-9aff-c1d74db08415.png)

**Comment by lory87** [comment]
@SteinRobert Can you please give me more information about your project? Which version, cms etc. Did you clear the cache or are there any errors in console? Thank you for your feedback.

**Comment by SteinRobert** [comment]
@lory87 sure. We are using Django 1.8.4, django-filer 1.2.0, Django CMS 3.2.3. There are no errors in the console, all files are served as expected. We did clear the cache, but that did not help either. Attached you can find our current environment:

------------------
Django==1.8.4
django-extensions
Django-Select2==5.8.4
Pillow==3.1.1
pysolr==3.4.0
Unidecode==0.04.19
argparse==1.2.1
cmsplugin-filer==1.0.1
django-appconf==1.0.1
django-classy-tags==0.7.2
django-cms==3.2.3
django-compressor==2.0
django-durationfield==0.5.2
django-filer==1.2.0
django-formtools==1.0
django-mptt==0.8.3
django-parler==1.6.2
django-polymorphic==0.9.1
django-reversion==1.10.1
django-sekizai==0.9.0
django-treebeard==4.0
djangocms-admin-style==1.1.0
djangocms-column==1.6.0
djangocms-flash==0.3.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-link==1.7.2
djangocms-style==1.7.0
djangocms-text-ckeditor==2.9.0
django-haystack==2.4.1
easy-thumbnails==2.3
html5lib==0.9999999
psycopg2==2.6.1
pytz==2016.2
rcssmin==1.0.6
rjsmin==1.0.12
six==1.10.0
wsgiref==0.1.2
django-debug-toolbar==1.4
django-countries==3.4.1
celery[redis]==3.1.19
django-celery==3.1.17
pyparsing==1.5.7
pydot==1.0.2  

------------------

**Comment by SteinRobert** [comment]
After executing `collectstatic` everything works as expected. 
Do you have an explanation? Why is it necessary only for django-filer in development with `DEBUG=True`?  Actually the `runserver` should manage to serve the staticfiles shouldn't it? Plus, as already mentioned, there just seems to be an issue with the `django-filer` files, even though there is no error in the console.
