### ISSUE TITLE
CSS issue delete button being obscured

### ISSUE THREAD

**Issue by codejoy** [django-cms/django-filer#859]
I also noticed this CSS issue (under runserver or apache) with the delete button allowing for delition of multiple selected files is obscured by the search bar.  Attached is an image of both chrome and firefox.

![filercssissue](https://cloud.githubusercontent.com/assets/225510/15792588/7eb1f870-299b-11e6-8a86-c613be1f38f8.png)

Would love to fix this, but not sure where or how.

**Comment by RadzionA** [comment]
Had same visual problem as on your picture in my Firefox 46.0.1.
**My Solution**:
1) Open file of styles in installed path
`/usr/local/lib/python3.4/dist-packages/filer/static/filer/css/admin_filer.css`
2) search for _**.filter-search-wrapper**_ style class
Change part of string
`width: calc(100% - 43px); `
to
`width: calc(100% - 50px); `
3) Search for **_.filter-files-container_** (many matches, more easy to find _245px_)
Change part of string
`width: 245px;`
to
`width: 400px;`
4) Save file
