### ISSUE TITLE
Hide "Thumbnail options" in Admin Backend

### ISSUE THREAD

**Issue by jrief** [django-cms/django-filer#864]
Thumbnail Options are only required, if you want to predefine image sizes. Some of my customers are confused about this setting and never need it. Would it be possible to add a configuration directive to not register this model in Django's Admin Backend?

**Comment by TheDeadOne** [comment]
**admin.py**
```
from filer.models import ThumbnailOption
admin.site.unregister(ThumbnailOption)
```
