### ISSUE TITLE
File list not refreshing upon upload in Firefox.

### ISSUE THREAD

**Issue by db654** [django-cms/django-filer#866]
It appears that, using Firefox 47.0 + Filer 1.2.0, after a successful file upload, the page doesn't refresh. I tested this in both Ubuntu and OS X, making sure to also try with all Add-ons disabled.

The same project works correctly in Chrome.

**Comment by DylannCordel** [comment]
:+1: with Firefox 45.3

The POST request returns a response with "application/json" as content-type but response is empty. Firefox seems to not accept empty Json response. Should return `{}`, `null` or `true` for exemple.

**Comment by DylannCordel** [comment]
It's fixed since 1.2.1 via #839.
Issue should be closed.
