### ISSUE TITLE
Permission problem for the root folder

### ISSUE THREAD

**Issue by vstoykov** [django-cms/django-filer#879]
When permissions are activated and `FILER_ALLOW_REGULAR_USERS_TO_ADD_ROOT_FOLDERS` is `False` there is no way to give permissions to any user to create folders in the root except if it is  a superuser (which I don't want).

I will try to prepare a PR.

**Comment by mtully-blitz** [comment]
Found a fix this using an undocumented setting:

`FILER_ALLOW_REGULAR_USERS_TO_ADD_ROOT_FOLDERS = True`

Here's the logic in the template code for the Add Folder button: https://github.com/divio/django-filer/blob/develop/filer/templates/admin/filer/folder/directory_listing.html#L212

can_make_folder is defined here: https://github.com/divio/django-filer/blob/develop/filer/admin/folderadmin.py#L450

**Comment by vstoykov** [comment]
@mtully-blitz I'm a little bit confused about your answer. I'm explicitly stating about:

    FILER_ALLOW_REGULAR_USERS_TO_ADD_ROOT_FOLDERS = False

This is because I don't want everybody do be able to create root folders. I also don't want only superusers to be able to create root folders. I need a way to give permissions to certain people which are not superusers to create root folders. Your **"fix"** is not a fix. It's a configuration that I don't want.

Am I missing something in your comment or you missed my issue?

The issue is old and for the project for which I needed this we figured some workaround which I can't remember right now.

**Comment by mtully-blitz** [comment]
@vstoykov looks like I misread. Could have sworn it referenced `FILER_ENABLE_PERMISSIONS`. I must have confused it with the referenced ticket.
