### ISSUE TITLE
Cannot upload SVG

### ISSUE THREAD

**Issue by lmanzurv** [django-cms/django-filer#885]
Hi,

I tried creating a Django CMS plugin for uploading SVG images. I followed the instructions under extending Django Filer, but using File as base, not BaseImage. On my local machine (using SQLite and local file storage) it works, but when I try to use the production setup (PostgreSQL + AWS S3), it breaks. In the error log I noticed that the MultiStorageFieldFile uses Thumbnailer which, when trying to save, throws the error StringIO instance has no attribute 'size' (I think it may have to with the fact that I'm using Django 1.8.9 because it breaks in a line self._size = content.size which is no longer in the latest Django version). Because of this, I cannot upload SVG files (nor from my plugin nor from the generic File definition inside filer).

Not actually sure if it's filer that's causing it because of Thumbnailer or if it's Django. Could you shed me some light?

**Comment by melbic** [comment]
The problem is possibly that gzip is activated for SVG files on S3. So the thumbnailer gets a gzip stream which it can't handle. As a workaround disable gzip for SVG files.

**Comment by lmanzurv** [comment]
OMG!! That was it! Django-storages had GZIP on and the default config compresses SVGs! And for what I saw, that's new. I just redefined the GZIP setting to exclude SVGs and it worked! Thank you very much!

**Comment by 10featj** [comment]
You can now upload images? and attack them to other tables using a CSV? PLEASE OH GOD PLEASE HELP ME
