### ISSUE TITLE
append filer use javascript???

### ISSUE THREAD

**Issue by ikhsanputra07** [django-cms/django-filer#890]
i want to append filer in my html template use jquery. After try, i success to do this. But when i click upload file in filer is'not redirect to popup upload file (admin/filer/folder/?_pick=file&_popup=1) but go to another link (admin/filer/folder/?_pick=file) without "&_popup=1".  I hope you can give me solution about this problem.

**Comment by kainbacher** [comment]
looks like you are missing some js files or you use old ones.
try to run "./manage.py collectstatic"
