### ISSUE TITLE
Default maximum file size is 256Mb

### ISSUE THREAD

**Issue by vxsx** [django-cms/django-filer#898]
Filer doesn't currently set the maximum file size limit in the frontend part, so it takes one from the library https://github.com/enyo/dropzone/blob/d8ef7a82e6ab5447c1f2d9512c8e1bfd4de5ac9e/dist/dropzone.js#L122

This should be configurable

**Comment by stefanfoulis** [comment]
There are also ``data-max-file-size="20"`` attributes throughout the code. I don't think they are currently used, but should also be cleaned up.
https://github.com/divio/django-filer/search?utf8=%E2%9C%93&q=data-max-file-size

**Comment by malaretv** [comment]
Is there any workaround for this? I'm bumping into this issue now

**Comment by petrklus** [comment]
Ditto - curious about this too.

**Comment by malaretv** [comment]
@petrklus not necessarily a fix... but I ended up having to implement the upload form in my own template with the dropzone library set to a higher limit appropriate for our case

**Comment by lunemec** [comment]
Uploading via the button works without limit (only nginx or uwsgi may limit this, which is configurable). So you can just not use the drag&drop option (or disable it?).
