### ISSUE TITLE
Dropzone 'mobile' CSS issues in size-constrained containers

### ISSUE THREAD

**Issue by Bartvds** [django-cms/django-filer#901]
The upload widget with the dropzone has a check on the width of the element and then toggles a mobile CSS class. This CSS doesn't work well with TabularInline's (used in the admin). 

It seems that the widget in this mobile mode adds vertical space, but the way it is implemented does nothing good for TabularInlines (the content gets pushed around or breaks the box):

![filer-css-1](https://cloud.githubusercontent.com/assets/685984/17522059/e9ee1d28-5e55-11e6-8578-0b465b39bd7a.png)

Also the dropzone is widget very large and doesn't fit in compact layouts (like TabularInlines with multiple fields, or custom templates, popups etc).

In our old app we have the old filer widget that was so much smaller and worked well besides other fields:

---

![filer-widget](https://cloud.githubusercontent.com/assets/685984/17521993/aefb5406-5e55-11e6-888d-c769e4188c28.png)

---

**Comment by benzkji** [comment]
I second this. It also does not initialize correctly when in a newly added inline (added with "add more"), but that's another issue...

**Comment by tdsymonds** [comment]
I had the same issue and have updated the styling to resolve it. I've added as pull request #908 that's pending approval, so hopefully it should be resolved in a future release. 

With my changes it now looks like:

![image](https://cloud.githubusercontent.com/assets/7289781/17932901/f52be2f0-6a09-11e6-9b6d-d2c64a909528.JPG)

Or with djangocms-admin-style:

![image 2](https://cloud.githubusercontent.com/assets/7289781/17933136/d40f2a9a-6a0a-11e6-9625-7a76cc1863a7.JPG)

**Comment by benzkji** [comment]
could be closed, I guess.
