### ISSUE TITLE
is uploading multiple files to admin at once possible?

### ISSUE THREAD

**Issue by ntorek** [django-cms/django-filer#903]
just wondering if it is possible to upload several files at once using the upload files popup in an admin model, or if django-filer actually limits you to only one per FilerFileField. the drag-files-here functionality makes it seem like you could pick more than one file to upload, but it is only letting me select one to save.

**Comment by benzkji** [comment]
FilerFileField is a models.ForeignKey to FilerFile, so it is technically not possible to accept/save more than one file for one field. You'll need to use inlines, for example (or create a custom inline, that accepts multiple uploads and creates the needed inlines with JS, for better usability).

**Comment by anil-python** [comment]
i am also facing same problem ,  i want to create zip of chosen file which selected at once , but not finding proper solutions.
