### ISSUE TITLE
AssertionError on delete files

### ISSUE THREAD

**Issue by itatelier** [django-cms/django-filer#932]
I got this error when deleting files from admin "Filer folders" view:

![image](https://cloud.githubusercontent.com/assets/7567335/20029550/d3ec0cc0-a35f-11e6-9993-c03636194ae1.png)

error appears after press "Yes" in confirmation form of delete_view
but when i try to delete from simple view by admin action "Delete selected.."(http://127.0.0.1:8000/admin/filer/image/) i got no errors.

using filer latest from develop branch

**Comment by yakky** [comment]
@itatelier Official Django 1.10 support will be released in 1.2.6. We are going to release an rc today and a final shortly after

**Comment by itatelier** [comment]
still have this issue on version 1.2.6

![image](https://cloud.githubusercontent.com/assets/7567335/22257953/c6513e82-e270-11e6-96dc-af8d53bc103a.png)

**Comment by ps91** [comment]
I'm also having this problem. Did you found any solution?

**Comment by itatelier** [comment]
Nope.. waiting =)

**Comment by itatelier** [comment]
Any news about it?
