### ISSUE TITLE
Image preview disappears after permissions change

### ISSUE THREAD

**Issue by Josca** [django-cms/django-filer#952]
Hi, I have a problem with permissions for image files. When I upload image into folder and it have permissions: disabled, everything is ok. But when I change its permissions to enabled, I can not see image preview any more. Image icon in directory listing is gone too. Is it bug or any additional setting is needed?

**Comment by jrief** [comment]
I order to reproduce this, I'd need a better description of that bug, for instance a fixture. Feel free to reopen.
