### ISSUE TITLE
Django v1.10 filer urls

### ISSUE THREAD

**Issue by dimkoug** [django-cms/django-filer#953]
I get NoReverseMatch 

NoReverseMatch: Reverse for 'filer-directory_listing-last'  

python 2.7/django 1.10

**Comment by thongly** [comment]
I get this when using a [custom admin site](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#overriding-default-admin-site).

Switching back to the default worked.  Don't have time to submit a PR for this right now, but just noting it here for others in the future.
