### ISSUE TITLE
Author field clashes with django 1.10.

### ISSUE THREAD

**Issue by mihalikv** [django-cms/django-filer#976]
Hello,

i am trying to use django-filer==1.2.7 with django 1.10 and django-cms 3.4.2. When i want to run migrations result is:
`filer.Image.author: (models.E006) The field 'author' clashes with the field 'author' from model 'filer.file'.`

My requirements are:

adal==0.4.5
appdirs==1.4.3
asn1crypto==0.22.0
azure==2.0.0rc6
azure-batch==1.0.0
azure-common==1.1.4
azure-mgmt==0.30.0rc6
azure-mgmt-batch==1.0.0
azure-mgmt-compute==0.30.0rc6
azure-mgmt-keyvault==0.30.0rc6
azure-mgmt-logic==1.0.0
azure-mgmt-network==0.30.0rc6
azure-mgmt-nspkg==1.0.0
azure-mgmt-redis==1.0.0
azure-mgmt-resource==0.30.0rc6
azure-mgmt-scheduler==1.0.0
azure-mgmt-storage==0.30.0rc6
azure-nspkg==1.0.0
azure-servicebus==0.20.3
azure-servicemanagement-legacy==0.20.4
azure-storage==0.20.0
beautifulsoup4==4.5.3
certifi==2017.4.17
cffi==1.10.0
cryptography==1.8.1
dj-database-url==0.4.2
Django==1.10
django-admin-sortable2==0.6.10
django-appconf==1.0.2
django-ckeditor==5.2.2
django-classy-tags==0.8.0
django-cms==3.4.2
django-constance==2.0.0
django-filer==1.2.7
django-filter==1.0.2
django-formtools==2.0
django-hitcount==1.2.2
django-jsonfield==1.0.1
django-mptt==0.8.7
django-multiselectfield==0.1.5
django-multiupload==0.5.2
django-picklefield==0.3.2
django-polymorphic==1.0.2
django-sekizai==0.10.0
Django-Select2==5.10.0
django-storages==1.5.2
django-taggit==0.22.0
django-treebeard==4.1.0
djangocms-admin-style==1.2.6.2
djangocms-attributes-field==0.2.0
djangocms-column==1.7.0
djangocms-googlemap==1.0.2
djangocms-inherit==0.2.2
djangocms-installer==0.9.6
djangocms-link==2.1.1
djangocms-picture==2.0.4
djangocms-style==2.0.2
djangocms-text-ckeditor==3.4.0
djangorestframework==3.6.2
easy-thumbnails==2.4.1
google-api-python-client==1.6.2
html5lib==0.999999
httplib2==0.10.3
idna==2.5
isodate==0.5.4
keyring==10.3.2
msrest==0.4.7
msrestazure==0.4.7
mutagen==1.37
oauth2client==4.0.0
oauthlib==2.0.2
olefile==0.44
packaging==16.8
Pillow==4.1.0
psycopg2==2.7.1
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
PyJWT==1.4.2
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2017.2
requests==2.13.0
requests-oauthlib==0.8.0
rsa==3.4.2
SecretStorage==2.3.1
simplejson==3.10.0
six==1.10.0
tinytag==0.17.0
tzlocal==1.4
Unidecode==0.4.20
uritemplate==3.0.0
webencodings==0.5.1
xlwt==1.2.0

Do you have some advice how fix this ?

**Comment by yakky** [comment]
I can't reprodce this. Is this still the case? Have you extended the image model
