### ISSUE TITLE
OSError: cannot write mode P as JPEG

### ISSUE THREAD

**Issue by sobolevn** [django-cms/django-filer#985]
When I try yo upload some image to the `django-filer` this happens:

> OSError at /ru/admin/filer/folder/unfiled_images/
> cannot write mode P as JPEG
> Request Method:	GET
> Request URL:	http://127.0.0.1:8000/ru/admin/filer/folder/unfiled_images/?_pick=file&_to_field=file_ptr&_popup=1&order_by=-modified_at
> Django Version:	1.10.7
> Exception Type:	OSError
> Exception Value:	
> cannot write mode P as JPEG
> Exception Location:	/Users/sobolev/.virtualenvs/peekaboo/lib/python3.6/site-packages/PIL/JpegImagePlugin.py in _save, line 604
> Python Executable:	/Users/sobolev/.virtualenvs/peekaboo/bin/python
> Python Version:	3.6.0
> Python Path:	
> ['/Users/sobolev/Documents/PyCharmProjects/peekaboo',
>  '/Users/sobolev/.virtualenvs/peekaboo/lib/python36.zip',
>  '/Users/sobolev/.virtualenvs/peekaboo/lib/python3.6',
>  '/Users/sobolev/.virtualenvs/peekaboo/lib/python3.6/lib-dynload',
>  '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6',
>  '/Users/sobolev/.virtualenvs/peekaboo/lib/python3.6/site-packages']
> Server time:	

On the other hand, some images work. 

Here are the lines that fail:

```python
def _save(im, fp, filename):
    try:
        rawmode = RAWMODE[im.mode]   # Here!
    except KeyError:
        raise IOError("cannot write mode %s as JPEG" % im.mode)
```

**Comment by joshuajonah** [comment]
This is clearly a permissions issue. Try making the target file location writable.

**Comment by sobolevn** [comment]
@joshuajonah double checked your idea. no, it is not. happens on multiple development machines with the same files.

**Comment by joshuajonah** [comment]
And those same files probably have the same permissions.

**Comment by sobolevn** [comment]
No, it is not a file-permission issue. 

Does this have something to do with file permissions?

```python
def _save(im, fp, filename):
    try:
        rawmode = RAWMODE[im.mode] 
    except KeyError:
        raise IOError("cannot write mode %s as JPEG" % im.mode)
```

**Comment by joshuajonah** [comment]
It looks like it's having trouble writing to disk, but this may be relevant: https://stackoverflow.com/questions/21669657/getting-cannot-write-mode-p-as-jpeg-while-operating-on-jpg-image
